// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  meta

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetStatusNotFound ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetStatusNotFound ) UnmarshalJSON([]byte) error { return nil }
func ( GetStatusNotFound ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetStatusNotFound ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetStatusNotFound *GetStatusNotFound

func ( GetStatusNotFoundList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetStatusNotFoundList ) UnmarshalJSON([]byte) error { return nil }
func ( GetStatusNotFoundList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetStatusNotFoundList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetStatusNotFoundList *GetStatusNotFoundList
