// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  meta

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetVerifyUnauthorized ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetVerifyUnauthorized ) UnmarshalJSON([]byte) error { return nil }
func ( GetVerifyUnauthorized ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetVerifyUnauthorized ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetVerifyUnauthorized *GetVerifyUnauthorized

func ( GetVerifyUnauthorizedList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetVerifyUnauthorizedList ) UnmarshalJSON([]byte) error { return nil }
func ( GetVerifyUnauthorizedList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetVerifyUnauthorizedList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetVerifyUnauthorizedList *GetVerifyUnauthorizedList
