// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  meta

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetVerifyError ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetVerifyError ) UnmarshalJSON([]byte) error { return nil }
func ( GetVerifyError ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetVerifyError ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetVerifyError *GetVerifyError

func ( GetVerifyErrorList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetVerifyErrorList ) UnmarshalJSON([]byte) error { return nil }
func ( GetVerifyErrorList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetVerifyErrorList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetVerifyErrorList *GetVerifyErrorList
