// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  meta

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetVerifyNotFound ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetVerifyNotFound ) UnmarshalJSON([]byte) error { return nil }
func ( GetVerifyNotFound ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetVerifyNotFound ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetVerifyNotFound *GetVerifyNotFound

func ( GetVerifyNotFoundList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetVerifyNotFoundList ) UnmarshalJSON([]byte) error { return nil }
func ( GetVerifyNotFoundList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetVerifyNotFoundList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetVerifyNotFoundList *GetVerifyNotFoundList
