// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  meta

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetVerifyOk ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetVerifyOk ) UnmarshalJSON([]byte) error { return nil }
func ( GetVerifyOk ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetVerifyOk ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetVerifyOk *GetVerifyOk

func ( GetVerifyOkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetVerifyOkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetVerifyOkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetVerifyOkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetVerifyOkList *GetVerifyOkList
