// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  meta

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetStatusItem ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetStatusItem ) UnmarshalJSON([]byte) error { return nil }
func ( GetStatusItem ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetStatusItem ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetStatusItem *GetStatusItem

func ( GetStatusItemList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetStatusItemList ) UnmarshalJSON([]byte) error { return nil }
func ( GetStatusItemList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetStatusItemList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetStatusItemList *GetStatusItemList
