// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCharactersCharacterIdClonesJumpClone ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdClonesJumpClone ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdClonesJumpClone ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdClonesJumpClone ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdClonesJumpClone *GetCharactersCharacterIdClonesJumpClone

func ( GetCharactersCharacterIdClonesJumpCloneList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdClonesJumpCloneList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdClonesJumpCloneList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdClonesJumpCloneList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdClonesJumpCloneList *GetCharactersCharacterIdClonesJumpCloneList
