// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCorporationsCorporationIdWalletsDivisionJournal200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdWalletsDivisionJournal200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdWalletsDivisionJournal200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdWalletsDivisionJournal200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdWalletsDivisionJournal200Ok *GetCorporationsCorporationIdWalletsDivisionJournal200Ok

func ( GetCorporationsCorporationIdWalletsDivisionJournal200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdWalletsDivisionJournal200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdWalletsDivisionJournal200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdWalletsDivisionJournal200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdWalletsDivisionJournal200OkList *GetCorporationsCorporationIdWalletsDivisionJournal200OkList
