// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCorporationCorporationIdMiningObservers200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationCorporationIdMiningObservers200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationCorporationIdMiningObservers200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationCorporationIdMiningObservers200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationCorporationIdMiningObservers200Ok *GetCorporationCorporationIdMiningObservers200Ok

func ( GetCorporationCorporationIdMiningObservers200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationCorporationIdMiningObservers200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationCorporationIdMiningObservers200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationCorporationIdMiningObservers200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationCorporationIdMiningObservers200OkList *GetCorporationCorporationIdMiningObservers200OkList
