// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCorporationsCorporationIdTitles200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdTitles200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdTitles200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdTitles200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdTitles200Ok *GetCorporationsCorporationIdTitles200Ok

func ( GetCorporationsCorporationIdTitles200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdTitles200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdTitles200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdTitles200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdTitles200OkList *GetCorporationsCorporationIdTitles200OkList
