// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetFleetsFleetIdMembersNotFound ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFleetsFleetIdMembersNotFound ) UnmarshalJSON([]byte) error { return nil }
func ( GetFleetsFleetIdMembersNotFound ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFleetsFleetIdMembersNotFound ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFleetsFleetIdMembersNotFound *GetFleetsFleetIdMembersNotFound

func ( GetFleetsFleetIdMembersNotFoundList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFleetsFleetIdMembersNotFoundList ) UnmarshalJSON([]byte) error { return nil }
func ( GetFleetsFleetIdMembersNotFoundList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFleetsFleetIdMembersNotFoundList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFleetsFleetIdMembersNotFoundList *GetFleetsFleetIdMembersNotFoundList
