// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCorporationCorporationIdMiningExtractions200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationCorporationIdMiningExtractions200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationCorporationIdMiningExtractions200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationCorporationIdMiningExtractions200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationCorporationIdMiningExtractions200Ok *GetCorporationCorporationIdMiningExtractions200Ok

func ( GetCorporationCorporationIdMiningExtractions200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationCorporationIdMiningExtractions200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationCorporationIdMiningExtractions200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationCorporationIdMiningExtractions200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationCorporationIdMiningExtractions200OkList *GetCorporationCorporationIdMiningExtractions200OkList
