// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCorporationsCorporationIdNotFound ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdNotFound ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdNotFound ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdNotFound ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdNotFound *GetCorporationsCorporationIdNotFound

func ( GetCorporationsCorporationIdNotFoundList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdNotFoundList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdNotFoundList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdNotFoundList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdNotFoundList *GetCorporationsCorporationIdNotFoundList
