// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( PostCorporationsCorporationIdAssetsLocationsNotFound ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostCorporationsCorporationIdAssetsLocationsNotFound ) UnmarshalJSON([]byte) error { return nil }
func ( PostCorporationsCorporationIdAssetsLocationsNotFound ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostCorporationsCorporationIdAssetsLocationsNotFound ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostCorporationsCorporationIdAssetsLocationsNotFound *PostCorporationsCorporationIdAssetsLocationsNotFound

func ( PostCorporationsCorporationIdAssetsLocationsNotFoundList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostCorporationsCorporationIdAssetsLocationsNotFoundList ) UnmarshalJSON([]byte) error { return nil }
func ( PostCorporationsCorporationIdAssetsLocationsNotFoundList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostCorporationsCorporationIdAssetsLocationsNotFoundList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostCorporationsCorporationIdAssetsLocationsNotFoundList *PostCorporationsCorporationIdAssetsLocationsNotFoundList
