// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetSovereigntyMap200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetSovereigntyMap200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetSovereigntyMap200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetSovereigntyMap200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetSovereigntyMap200Ok *GetSovereigntyMap200Ok

func ( GetSovereigntyMap200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetSovereigntyMap200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetSovereigntyMap200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetSovereigntyMap200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetSovereigntyMap200OkList *GetSovereigntyMap200OkList
