// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( PostCharactersCharacterIdFittingsItem ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostCharactersCharacterIdFittingsItem ) UnmarshalJSON([]byte) error { return nil }
func ( PostCharactersCharacterIdFittingsItem ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostCharactersCharacterIdFittingsItem ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostCharactersCharacterIdFittingsItem *PostCharactersCharacterIdFittingsItem

func ( PostCharactersCharacterIdFittingsItemList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostCharactersCharacterIdFittingsItemList ) UnmarshalJSON([]byte) error { return nil }
func ( PostCharactersCharacterIdFittingsItemList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostCharactersCharacterIdFittingsItemList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostCharactersCharacterIdFittingsItemList *PostCharactersCharacterIdFittingsItemList
