// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCharactersCharacterIdContractsContractIdItemsNotFound ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdContractsContractIdItemsNotFound ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdContractsContractIdItemsNotFound ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdContractsContractIdItemsNotFound ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdContractsContractIdItemsNotFound *GetCharactersCharacterIdContractsContractIdItemsNotFound

func ( GetCharactersCharacterIdContractsContractIdItemsNotFoundList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdContractsContractIdItemsNotFoundList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdContractsContractIdItemsNotFoundList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdContractsContractIdItemsNotFoundList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdContractsContractIdItemsNotFoundList *GetCharactersCharacterIdContractsContractIdItemsNotFoundList
