// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCharactersCharacterIdOnlineOk ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdOnlineOk ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdOnlineOk ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdOnlineOk ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdOnlineOk *GetCharactersCharacterIdOnlineOk

func ( GetCharactersCharacterIdOnlineOkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdOnlineOkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdOnlineOkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdOnlineOkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdOnlineOkList *GetCharactersCharacterIdOnlineOkList
