// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCharactersCharacterIdPlanetsPlanetIdNotFound ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdPlanetsPlanetIdNotFound ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdPlanetsPlanetIdNotFound ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdPlanetsPlanetIdNotFound ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdPlanetsPlanetIdNotFound *GetCharactersCharacterIdPlanetsPlanetIdNotFound

func ( GetCharactersCharacterIdPlanetsPlanetIdNotFoundList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdPlanetsPlanetIdNotFoundList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdPlanetsPlanetIdNotFoundList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdPlanetsPlanetIdNotFoundList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdPlanetsPlanetIdNotFoundList *GetCharactersCharacterIdPlanetsPlanetIdNotFoundList
