// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCharactersCharacterIdAgentsResearch200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdAgentsResearch200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdAgentsResearch200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdAgentsResearch200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdAgentsResearch200Ok *GetCharactersCharacterIdAgentsResearch200Ok

func ( GetCharactersCharacterIdAgentsResearch200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdAgentsResearch200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdAgentsResearch200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdAgentsResearch200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdAgentsResearch200OkList *GetCharactersCharacterIdAgentsResearch200OkList
