// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCharactersCharacterIdCalendarEventIdNotFound ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdCalendarEventIdNotFound ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdCalendarEventIdNotFound ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdCalendarEventIdNotFound ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdCalendarEventIdNotFound *GetCharactersCharacterIdCalendarEventIdNotFound

func ( GetCharactersCharacterIdCalendarEventIdNotFoundList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdCalendarEventIdNotFoundList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdCalendarEventIdNotFoundList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdCalendarEventIdNotFoundList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdCalendarEventIdNotFoundList *GetCharactersCharacterIdCalendarEventIdNotFoundList
