// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetAlliancesAllianceIdIconsOk ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetAlliancesAllianceIdIconsOk ) UnmarshalJSON([]byte) error { return nil }
func ( GetAlliancesAllianceIdIconsOk ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetAlliancesAllianceIdIconsOk ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetAlliancesAllianceIdIconsOk *GetAlliancesAllianceIdIconsOk

func ( GetAlliancesAllianceIdIconsOkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetAlliancesAllianceIdIconsOkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetAlliancesAllianceIdIconsOkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetAlliancesAllianceIdIconsOkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetAlliancesAllianceIdIconsOkList *GetAlliancesAllianceIdIconsOkList
