// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCharactersCharacterIdContactsLabels200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdContactsLabels200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdContactsLabels200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdContactsLabels200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdContactsLabels200Ok *GetCharactersCharacterIdContactsLabels200Ok

func ( GetCharactersCharacterIdContactsLabels200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdContactsLabels200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdContactsLabels200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdContactsLabels200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdContactsLabels200OkList *GetCharactersCharacterIdContactsLabels200OkList
