// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetMarketsGroupsMarketGroupIdNotFound ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetMarketsGroupsMarketGroupIdNotFound ) UnmarshalJSON([]byte) error { return nil }
func ( GetMarketsGroupsMarketGroupIdNotFound ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetMarketsGroupsMarketGroupIdNotFound ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetMarketsGroupsMarketGroupIdNotFound *GetMarketsGroupsMarketGroupIdNotFound

func ( GetMarketsGroupsMarketGroupIdNotFoundList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetMarketsGroupsMarketGroupIdNotFoundList ) UnmarshalJSON([]byte) error { return nil }
func ( GetMarketsGroupsMarketGroupIdNotFoundList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetMarketsGroupsMarketGroupIdNotFoundList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetMarketsGroupsMarketGroupIdNotFoundList *GetMarketsGroupsMarketGroupIdNotFoundList
