// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCharactersCharacterIdFwStatsVictoryPoints ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdFwStatsVictoryPoints ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdFwStatsVictoryPoints ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdFwStatsVictoryPoints ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdFwStatsVictoryPoints *GetCharactersCharacterIdFwStatsVictoryPoints

func ( GetCharactersCharacterIdFwStatsVictoryPointsList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdFwStatsVictoryPointsList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdFwStatsVictoryPointsList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdFwStatsVictoryPointsList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdFwStatsVictoryPointsList *GetCharactersCharacterIdFwStatsVictoryPointsList
