// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetInsurancePrices200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetInsurancePrices200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetInsurancePrices200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetInsurancePrices200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetInsurancePrices200Ok *GetInsurancePrices200Ok

func ( GetInsurancePrices200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetInsurancePrices200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetInsurancePrices200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetInsurancePrices200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetInsurancePrices200OkList *GetInsurancePrices200OkList
