// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetUniversePlanetsPlanetIdPosition ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniversePlanetsPlanetIdPosition ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniversePlanetsPlanetIdPosition ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniversePlanetsPlanetIdPosition ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniversePlanetsPlanetIdPosition *GetUniversePlanetsPlanetIdPosition

func ( GetUniversePlanetsPlanetIdPositionList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniversePlanetsPlanetIdPositionList ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniversePlanetsPlanetIdPositionList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniversePlanetsPlanetIdPositionList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniversePlanetsPlanetIdPositionList *GetUniversePlanetsPlanetIdPositionList
