// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetUniverseRegionsRegionIdNotFound ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseRegionsRegionIdNotFound ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseRegionsRegionIdNotFound ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseRegionsRegionIdNotFound ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseRegionsRegionIdNotFound *GetUniverseRegionsRegionIdNotFound

func ( GetUniverseRegionsRegionIdNotFoundList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseRegionsRegionIdNotFoundList ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseRegionsRegionIdNotFoundList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseRegionsRegionIdNotFoundList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseRegionsRegionIdNotFoundList *GetUniverseRegionsRegionIdNotFoundList
