// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCharactersCharacterIdPortraitOk ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdPortraitOk ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdPortraitOk ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdPortraitOk ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdPortraitOk *GetCharactersCharacterIdPortraitOk

func ( GetCharactersCharacterIdPortraitOkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdPortraitOkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdPortraitOkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdPortraitOkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdPortraitOkList *GetCharactersCharacterIdPortraitOkList
