// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetKillmailsKillmailIdKillmailHashOk ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetKillmailsKillmailIdKillmailHashOk ) UnmarshalJSON([]byte) error { return nil }
func ( GetKillmailsKillmailIdKillmailHashOk ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetKillmailsKillmailIdKillmailHashOk ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetKillmailsKillmailIdKillmailHashOk *GetKillmailsKillmailIdKillmailHashOk

func ( GetKillmailsKillmailIdKillmailHashOkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetKillmailsKillmailIdKillmailHashOkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetKillmailsKillmailIdKillmailHashOkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetKillmailsKillmailIdKillmailHashOkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetKillmailsKillmailIdKillmailHashOkList *GetKillmailsKillmailIdKillmailHashOkList
