// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCorporationsCorporationIdMedalsIssued200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdMedalsIssued200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdMedalsIssued200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdMedalsIssued200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdMedalsIssued200Ok *GetCorporationsCorporationIdMedalsIssued200Ok

func ( GetCorporationsCorporationIdMedalsIssued200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdMedalsIssued200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdMedalsIssued200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdMedalsIssued200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdMedalsIssued200OkList *GetCorporationsCorporationIdMedalsIssued200OkList
