// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetWarsWarIdUnprocessableEntity ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetWarsWarIdUnprocessableEntity ) UnmarshalJSON([]byte) error { return nil }
func ( GetWarsWarIdUnprocessableEntity ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetWarsWarIdUnprocessableEntity ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetWarsWarIdUnprocessableEntity *GetWarsWarIdUnprocessableEntity

func ( GetWarsWarIdUnprocessableEntityList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetWarsWarIdUnprocessableEntityList ) UnmarshalJSON([]byte) error { return nil }
func ( GetWarsWarIdUnprocessableEntityList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetWarsWarIdUnprocessableEntityList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetWarsWarIdUnprocessableEntityList *GetWarsWarIdUnprocessableEntityList
