// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetFwLeaderboardsVictoryPoints ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFwLeaderboardsVictoryPoints ) UnmarshalJSON([]byte) error { return nil }
func ( GetFwLeaderboardsVictoryPoints ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFwLeaderboardsVictoryPoints ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFwLeaderboardsVictoryPoints *GetFwLeaderboardsVictoryPoints

func ( GetFwLeaderboardsVictoryPointsList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFwLeaderboardsVictoryPointsList ) UnmarshalJSON([]byte) error { return nil }
func ( GetFwLeaderboardsVictoryPointsList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFwLeaderboardsVictoryPointsList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFwLeaderboardsVictoryPointsList *GetFwLeaderboardsVictoryPointsList
