// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCharactersCharacterIdMailRecipient ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdMailRecipient ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdMailRecipient ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdMailRecipient ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdMailRecipient *GetCharactersCharacterIdMailRecipient

func ( GetCharactersCharacterIdMailRecipientList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdMailRecipientList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdMailRecipientList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdMailRecipientList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdMailRecipientList *GetCharactersCharacterIdMailRecipientList
