// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCorporationsCorporationIdMembersTitles200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdMembersTitles200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdMembersTitles200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdMembersTitles200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdMembersTitles200Ok *GetCorporationsCorporationIdMembersTitles200Ok

func ( GetCorporationsCorporationIdMembersTitles200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdMembersTitles200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdMembersTitles200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdMembersTitles200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdMembersTitles200OkList *GetCorporationsCorporationIdMembersTitles200OkList
