// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetFwLeaderboardsCorporationsLastWeekLastWeek ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFwLeaderboardsCorporationsLastWeekLastWeek ) UnmarshalJSON([]byte) error { return nil }
func ( GetFwLeaderboardsCorporationsLastWeekLastWeek ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFwLeaderboardsCorporationsLastWeekLastWeek ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFwLeaderboardsCorporationsLastWeekLastWeek *GetFwLeaderboardsCorporationsLastWeekLastWeek

func ( GetFwLeaderboardsCorporationsLastWeekLastWeekList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFwLeaderboardsCorporationsLastWeekLastWeekList ) UnmarshalJSON([]byte) error { return nil }
func ( GetFwLeaderboardsCorporationsLastWeekLastWeekList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFwLeaderboardsCorporationsLastWeekLastWeekList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFwLeaderboardsCorporationsLastWeekLastWeekList *GetFwLeaderboardsCorporationsLastWeekLastWeekList
