// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCharactersCharacterIdSearchOk ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdSearchOk ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdSearchOk ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdSearchOk ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdSearchOk *GetCharactersCharacterIdSearchOk

func ( GetCharactersCharacterIdSearchOkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdSearchOkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdSearchOkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdSearchOkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdSearchOkList *GetCharactersCharacterIdSearchOkList
