// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( PutFleetsFleetIdNewSettings ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PutFleetsFleetIdNewSettings ) UnmarshalJSON([]byte) error { return nil }
func ( PutFleetsFleetIdNewSettings ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PutFleetsFleetIdNewSettings ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PutFleetsFleetIdNewSettings *PutFleetsFleetIdNewSettings

func ( PutFleetsFleetIdNewSettingsList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PutFleetsFleetIdNewSettingsList ) UnmarshalJSON([]byte) error { return nil }
func ( PutFleetsFleetIdNewSettingsList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PutFleetsFleetIdNewSettingsList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PutFleetsFleetIdNewSettingsList *PutFleetsFleetIdNewSettingsList
