// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( PostUniverseNamesNotFound ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostUniverseNamesNotFound ) UnmarshalJSON([]byte) error { return nil }
func ( PostUniverseNamesNotFound ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostUniverseNamesNotFound ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostUniverseNamesNotFound *PostUniverseNamesNotFound

func ( PostUniverseNamesNotFoundList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostUniverseNamesNotFoundList ) UnmarshalJSON([]byte) error { return nil }
func ( PostUniverseNamesNotFoundList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostUniverseNamesNotFoundList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostUniverseNamesNotFoundList *PostUniverseNamesNotFoundList
