// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( PutFleetsFleetIdMembersMemberIdUnprocessableEntity ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PutFleetsFleetIdMembersMemberIdUnprocessableEntity ) UnmarshalJSON([]byte) error { return nil }
func ( PutFleetsFleetIdMembersMemberIdUnprocessableEntity ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PutFleetsFleetIdMembersMemberIdUnprocessableEntity ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PutFleetsFleetIdMembersMemberIdUnprocessableEntity *PutFleetsFleetIdMembersMemberIdUnprocessableEntity

func ( PutFleetsFleetIdMembersMemberIdUnprocessableEntityList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PutFleetsFleetIdMembersMemberIdUnprocessableEntityList ) UnmarshalJSON([]byte) error { return nil }
func ( PutFleetsFleetIdMembersMemberIdUnprocessableEntityList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PutFleetsFleetIdMembersMemberIdUnprocessableEntityList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PutFleetsFleetIdMembersMemberIdUnprocessableEntityList *PutFleetsFleetIdMembersMemberIdUnprocessableEntityList
