// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCharactersCharacterIdBlueprints200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdBlueprints200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdBlueprints200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdBlueprints200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdBlueprints200Ok *GetCharactersCharacterIdBlueprints200Ok

func ( GetCharactersCharacterIdBlueprints200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdBlueprints200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdBlueprints200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdBlueprints200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdBlueprints200OkList *GetCharactersCharacterIdBlueprints200OkList
