// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( PostCharactersCharacterIdAssetsLocations200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostCharactersCharacterIdAssetsLocations200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( PostCharactersCharacterIdAssetsLocations200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostCharactersCharacterIdAssetsLocations200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostCharactersCharacterIdAssetsLocations200Ok *PostCharactersCharacterIdAssetsLocations200Ok

func ( PostCharactersCharacterIdAssetsLocations200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostCharactersCharacterIdAssetsLocations200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( PostCharactersCharacterIdAssetsLocations200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostCharactersCharacterIdAssetsLocations200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostCharactersCharacterIdAssetsLocations200OkList *PostCharactersCharacterIdAssetsLocations200OkList
