// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCharactersCharacterIdNotificationsContacts200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdNotificationsContacts200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdNotificationsContacts200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdNotificationsContacts200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdNotificationsContacts200Ok *GetCharactersCharacterIdNotificationsContacts200Ok

func ( GetCharactersCharacterIdNotificationsContacts200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdNotificationsContacts200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdNotificationsContacts200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdNotificationsContacts200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdNotificationsContacts200OkList *GetCharactersCharacterIdNotificationsContacts200OkList
