// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetUniverseMoonsMoonIdNotFound ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseMoonsMoonIdNotFound ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseMoonsMoonIdNotFound ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseMoonsMoonIdNotFound ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseMoonsMoonIdNotFound *GetUniverseMoonsMoonIdNotFound

func ( GetUniverseMoonsMoonIdNotFoundList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseMoonsMoonIdNotFoundList ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseMoonsMoonIdNotFoundList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseMoonsMoonIdNotFoundList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseMoonsMoonIdNotFoundList *GetUniverseMoonsMoonIdNotFoundList
