// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( PostUniverseIdsAgent ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostUniverseIdsAgent ) UnmarshalJSON([]byte) error { return nil }
func ( PostUniverseIdsAgent ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostUniverseIdsAgent ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostUniverseIdsAgent *PostUniverseIdsAgent

func ( PostUniverseIdsAgentList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostUniverseIdsAgentList ) UnmarshalJSON([]byte) error { return nil }
func ( PostUniverseIdsAgentList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostUniverseIdsAgentList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostUniverseIdsAgentList *PostUniverseIdsAgentList
