// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCharactersCharacterIdPlanetsPlanetIdHead ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdPlanetsPlanetIdHead ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdPlanetsPlanetIdHead ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdPlanetsPlanetIdHead ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdPlanetsPlanetIdHead *GetCharactersCharacterIdPlanetsPlanetIdHead

func ( GetCharactersCharacterIdPlanetsPlanetIdHeadList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdPlanetsPlanetIdHeadList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdPlanetsPlanetIdHeadList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdPlanetsPlanetIdHeadList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdPlanetsPlanetIdHeadList *GetCharactersCharacterIdPlanetsPlanetIdHeadList
