// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCorporationsCorporationIdOk ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdOk ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdOk ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdOk ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdOk *GetCorporationsCorporationIdOk

func ( GetCorporationsCorporationIdOkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdOkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdOkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdOkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdOkList *GetCorporationsCorporationIdOkList
