// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetFwStatsKills ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFwStatsKills ) UnmarshalJSON([]byte) error { return nil }
func ( GetFwStatsKills ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFwStatsKills ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFwStatsKills *GetFwStatsKills

func ( GetFwStatsKillsList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFwStatsKillsList ) UnmarshalJSON([]byte) error { return nil }
func ( GetFwStatsKillsList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFwStatsKillsList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFwStatsKillsList *GetFwStatsKillsList
