// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetFwStatsVictoryPoints ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFwStatsVictoryPoints ) UnmarshalJSON([]byte) error { return nil }
func ( GetFwStatsVictoryPoints ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFwStatsVictoryPoints ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFwStatsVictoryPoints *GetFwStatsVictoryPoints

func ( GetFwStatsVictoryPointsList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFwStatsVictoryPointsList ) UnmarshalJSON([]byte) error { return nil }
func ( GetFwStatsVictoryPointsList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFwStatsVictoryPointsList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFwStatsVictoryPointsList *GetFwStatsVictoryPointsList
