// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetUniverseStargatesStargateIdDestination ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseStargatesStargateIdDestination ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseStargatesStargateIdDestination ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseStargatesStargateIdDestination ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseStargatesStargateIdDestination *GetUniverseStargatesStargateIdDestination

func ( GetUniverseStargatesStargateIdDestinationList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseStargatesStargateIdDestinationList ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseStargatesStargateIdDestinationList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseStargatesStargateIdDestinationList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseStargatesStargateIdDestinationList *GetUniverseStargatesStargateIdDestinationList
