// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetIncursions200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetIncursions200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetIncursions200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetIncursions200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetIncursions200Ok *GetIncursions200Ok

func ( GetIncursions200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetIncursions200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetIncursions200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetIncursions200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetIncursions200OkList *GetIncursions200OkList
