// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCorporationsCorporationIdContractsContractIdItems200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdContractsContractIdItems200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdContractsContractIdItems200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdContractsContractIdItems200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdContractsContractIdItems200Ok *GetCorporationsCorporationIdContractsContractIdItems200Ok

func ( GetCorporationsCorporationIdContractsContractIdItems200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdContractsContractIdItems200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdContractsContractIdItems200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdContractsContractIdItems200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdContractsContractIdItems200OkList *GetCorporationsCorporationIdContractsContractIdItems200OkList
