// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetUniverseSystemsSystemIdNotFound ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseSystemsSystemIdNotFound ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseSystemsSystemIdNotFound ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseSystemsSystemIdNotFound ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseSystemsSystemIdNotFound *GetUniverseSystemsSystemIdNotFound

func ( GetUniverseSystemsSystemIdNotFoundList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseSystemsSystemIdNotFoundList ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseSystemsSystemIdNotFoundList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseSystemsSystemIdNotFoundList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseSystemsSystemIdNotFoundList *GetUniverseSystemsSystemIdNotFoundList
