// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetRouteOriginDestinationNotFound ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetRouteOriginDestinationNotFound ) UnmarshalJSON([]byte) error { return nil }
func ( GetRouteOriginDestinationNotFound ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetRouteOriginDestinationNotFound ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetRouteOriginDestinationNotFound *GetRouteOriginDestinationNotFound

func ( GetRouteOriginDestinationNotFoundList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetRouteOriginDestinationNotFoundList ) UnmarshalJSON([]byte) error { return nil }
func ( GetRouteOriginDestinationNotFoundList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetRouteOriginDestinationNotFoundList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetRouteOriginDestinationNotFoundList *GetRouteOriginDestinationNotFoundList
