// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetDogmaAttributesAttributeIdOk ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetDogmaAttributesAttributeIdOk ) UnmarshalJSON([]byte) error { return nil }
func ( GetDogmaAttributesAttributeIdOk ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetDogmaAttributesAttributeIdOk ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetDogmaAttributesAttributeIdOk *GetDogmaAttributesAttributeIdOk

func ( GetDogmaAttributesAttributeIdOkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetDogmaAttributesAttributeIdOkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetDogmaAttributesAttributeIdOkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetDogmaAttributesAttributeIdOkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetDogmaAttributesAttributeIdOkList *GetDogmaAttributesAttributeIdOkList
