// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( PostUiOpenwindowNewmailNewMail ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostUiOpenwindowNewmailNewMail ) UnmarshalJSON([]byte) error { return nil }
func ( PostUiOpenwindowNewmailNewMail ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostUiOpenwindowNewmailNewMail ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostUiOpenwindowNewmailNewMail *PostUiOpenwindowNewmailNewMail

func ( PostUiOpenwindowNewmailNewMailList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostUiOpenwindowNewmailNewMailList ) UnmarshalJSON([]byte) error { return nil }
func ( PostUiOpenwindowNewmailNewMailList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostUiOpenwindowNewmailNewMailList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostUiOpenwindowNewmailNewMailList *PostUiOpenwindowNewmailNewMailList
