// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCorporationsCorporationIdShareholders200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdShareholders200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdShareholders200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdShareholders200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdShareholders200Ok *GetCorporationsCorporationIdShareholders200Ok

func ( GetCorporationsCorporationIdShareholders200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdShareholders200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdShareholders200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdShareholders200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdShareholders200OkList *GetCorporationsCorporationIdShareholders200OkList
