// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetFwLeaderboardsLastWeekLastWeek ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFwLeaderboardsLastWeekLastWeek ) UnmarshalJSON([]byte) error { return nil }
func ( GetFwLeaderboardsLastWeekLastWeek ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFwLeaderboardsLastWeekLastWeek ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFwLeaderboardsLastWeekLastWeek *GetFwLeaderboardsLastWeekLastWeek

func ( GetFwLeaderboardsLastWeekLastWeekList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFwLeaderboardsLastWeekLastWeekList ) UnmarshalJSON([]byte) error { return nil }
func ( GetFwLeaderboardsLastWeekLastWeekList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFwLeaderboardsLastWeekLastWeekList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFwLeaderboardsLastWeekLastWeekList *GetFwLeaderboardsLastWeekLastWeekList
