// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetUniversePlanetsPlanetIdNotFound ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniversePlanetsPlanetIdNotFound ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniversePlanetsPlanetIdNotFound ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniversePlanetsPlanetIdNotFound ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniversePlanetsPlanetIdNotFound *GetUniversePlanetsPlanetIdNotFound

func ( GetUniversePlanetsPlanetIdNotFoundList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniversePlanetsPlanetIdNotFoundList ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniversePlanetsPlanetIdNotFoundList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniversePlanetsPlanetIdNotFoundList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniversePlanetsPlanetIdNotFoundList *GetUniversePlanetsPlanetIdNotFoundList
