// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetLoyaltyStoresCorporationIdOffersNotFound ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetLoyaltyStoresCorporationIdOffersNotFound ) UnmarshalJSON([]byte) error { return nil }
func ( GetLoyaltyStoresCorporationIdOffersNotFound ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetLoyaltyStoresCorporationIdOffersNotFound ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetLoyaltyStoresCorporationIdOffersNotFound *GetLoyaltyStoresCorporationIdOffersNotFound

func ( GetLoyaltyStoresCorporationIdOffersNotFoundList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetLoyaltyStoresCorporationIdOffersNotFoundList ) UnmarshalJSON([]byte) error { return nil }
func ( GetLoyaltyStoresCorporationIdOffersNotFoundList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetLoyaltyStoresCorporationIdOffersNotFoundList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetLoyaltyStoresCorporationIdOffersNotFoundList *GetLoyaltyStoresCorporationIdOffersNotFoundList
