// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetUniverseSchematicsSchematicIdNotFound ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseSchematicsSchematicIdNotFound ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseSchematicsSchematicIdNotFound ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseSchematicsSchematicIdNotFound ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseSchematicsSchematicIdNotFound *GetUniverseSchematicsSchematicIdNotFound

func ( GetUniverseSchematicsSchematicIdNotFoundList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseSchematicsSchematicIdNotFoundList ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseSchematicsSchematicIdNotFoundList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseSchematicsSchematicIdNotFoundList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseSchematicsSchematicIdNotFoundList *GetUniverseSchematicsSchematicIdNotFoundList
