// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( PutFleetsFleetIdSquadsSquadIdNaming ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PutFleetsFleetIdSquadsSquadIdNaming ) UnmarshalJSON([]byte) error { return nil }
func ( PutFleetsFleetIdSquadsSquadIdNaming ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PutFleetsFleetIdSquadsSquadIdNaming ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PutFleetsFleetIdSquadsSquadIdNaming *PutFleetsFleetIdSquadsSquadIdNaming

func ( PutFleetsFleetIdSquadsSquadIdNamingList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PutFleetsFleetIdSquadsSquadIdNamingList ) UnmarshalJSON([]byte) error { return nil }
func ( PutFleetsFleetIdSquadsSquadIdNamingList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PutFleetsFleetIdSquadsSquadIdNamingList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PutFleetsFleetIdSquadsSquadIdNamingList *PutFleetsFleetIdSquadsSquadIdNamingList
