// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetUniverseStructuresStructureIdOk ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseStructuresStructureIdOk ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseStructuresStructureIdOk ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseStructuresStructureIdOk ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseStructuresStructureIdOk *GetUniverseStructuresStructureIdOk

func ( GetUniverseStructuresStructureIdOkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseStructuresStructureIdOkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseStructuresStructureIdOkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseStructuresStructureIdOkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseStructuresStructureIdOkList *GetUniverseStructuresStructureIdOkList
