// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetWarsWarIdKillmailsUnprocessableEntity ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetWarsWarIdKillmailsUnprocessableEntity ) UnmarshalJSON([]byte) error { return nil }
func ( GetWarsWarIdKillmailsUnprocessableEntity ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetWarsWarIdKillmailsUnprocessableEntity ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetWarsWarIdKillmailsUnprocessableEntity *GetWarsWarIdKillmailsUnprocessableEntity

func ( GetWarsWarIdKillmailsUnprocessableEntityList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetWarsWarIdKillmailsUnprocessableEntityList ) UnmarshalJSON([]byte) error { return nil }
func ( GetWarsWarIdKillmailsUnprocessableEntityList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetWarsWarIdKillmailsUnprocessableEntityList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetWarsWarIdKillmailsUnprocessableEntityList *GetWarsWarIdKillmailsUnprocessableEntityList
