// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCharactersCharacterIdOk ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdOk ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdOk ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdOk ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdOk *GetCharactersCharacterIdOk

func ( GetCharactersCharacterIdOkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdOkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdOkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdOkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdOkList *GetCharactersCharacterIdOkList
