// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetFwLeaderboardsCorporationsYesterdayYesterday1 ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFwLeaderboardsCorporationsYesterdayYesterday1 ) UnmarshalJSON([]byte) error { return nil }
func ( GetFwLeaderboardsCorporationsYesterdayYesterday1 ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFwLeaderboardsCorporationsYesterdayYesterday1 ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFwLeaderboardsCorporationsYesterdayYesterday1 *GetFwLeaderboardsCorporationsYesterdayYesterday1

func ( GetFwLeaderboardsCorporationsYesterdayYesterday1List ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFwLeaderboardsCorporationsYesterdayYesterday1List ) UnmarshalJSON([]byte) error { return nil }
func ( GetFwLeaderboardsCorporationsYesterdayYesterday1List ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFwLeaderboardsCorporationsYesterdayYesterday1List ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFwLeaderboardsCorporationsYesterdayYesterday1List *GetFwLeaderboardsCorporationsYesterdayYesterday1List
