// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCharactersCharacterIdAssets200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdAssets200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdAssets200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdAssets200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdAssets200Ok *GetCharactersCharacterIdAssets200Ok

func ( GetCharactersCharacterIdAssets200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdAssets200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdAssets200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdAssets200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdAssets200OkList *GetCharactersCharacterIdAssets200OkList
