// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCharactersCharacterIdPortraitNotFound ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdPortraitNotFound ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdPortraitNotFound ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdPortraitNotFound ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdPortraitNotFound *GetCharactersCharacterIdPortraitNotFound

func ( GetCharactersCharacterIdPortraitNotFoundList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdPortraitNotFoundList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdPortraitNotFoundList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdPortraitNotFoundList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdPortraitNotFoundList *GetCharactersCharacterIdPortraitNotFoundList
