// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCorporationsCorporationIdCustomsOffices200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdCustomsOffices200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdCustomsOffices200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdCustomsOffices200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdCustomsOffices200Ok *GetCorporationsCorporationIdCustomsOffices200Ok

func ( GetCorporationsCorporationIdCustomsOffices200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdCustomsOffices200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdCustomsOffices200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdCustomsOffices200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdCustomsOffices200OkList *GetCorporationsCorporationIdCustomsOffices200OkList
