// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetSovereigntyCampaigns200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetSovereigntyCampaigns200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetSovereigntyCampaigns200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetSovereigntyCampaigns200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetSovereigntyCampaigns200Ok *GetSovereigntyCampaigns200Ok

func ( GetSovereigntyCampaigns200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetSovereigntyCampaigns200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetSovereigntyCampaigns200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetSovereigntyCampaigns200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetSovereigntyCampaigns200OkList *GetSovereigntyCampaigns200OkList
