// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCharactersCharacterIdFwStatsOk ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdFwStatsOk ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdFwStatsOk ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdFwStatsOk ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdFwStatsOk *GetCharactersCharacterIdFwStatsOk

func ( GetCharactersCharacterIdFwStatsOkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdFwStatsOkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdFwStatsOkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdFwStatsOkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdFwStatsOkList *GetCharactersCharacterIdFwStatsOkList
