// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetFwLeaderboardsActiveTotalActiveTotal1 ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFwLeaderboardsActiveTotalActiveTotal1 ) UnmarshalJSON([]byte) error { return nil }
func ( GetFwLeaderboardsActiveTotalActiveTotal1 ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFwLeaderboardsActiveTotalActiveTotal1 ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFwLeaderboardsActiveTotalActiveTotal1 *GetFwLeaderboardsActiveTotalActiveTotal1

func ( GetFwLeaderboardsActiveTotalActiveTotal1List ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFwLeaderboardsActiveTotalActiveTotal1List ) UnmarshalJSON([]byte) error { return nil }
func ( GetFwLeaderboardsActiveTotalActiveTotal1List ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFwLeaderboardsActiveTotalActiveTotal1List ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFwLeaderboardsActiveTotalActiveTotal1List *GetFwLeaderboardsActiveTotalActiveTotal1List
