// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetFleetsFleetIdWings200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFleetsFleetIdWings200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetFleetsFleetIdWings200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFleetsFleetIdWings200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFleetsFleetIdWings200Ok *GetFleetsFleetIdWings200Ok

func ( GetFleetsFleetIdWings200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFleetsFleetIdWings200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetFleetsFleetIdWings200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFleetsFleetIdWings200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFleetsFleetIdWings200OkList *GetFleetsFleetIdWings200OkList
