// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( PostUiOpenwindowNewmailUnprocessableEntity ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostUiOpenwindowNewmailUnprocessableEntity ) UnmarshalJSON([]byte) error { return nil }
func ( PostUiOpenwindowNewmailUnprocessableEntity ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostUiOpenwindowNewmailUnprocessableEntity ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostUiOpenwindowNewmailUnprocessableEntity *PostUiOpenwindowNewmailUnprocessableEntity

func ( PostUiOpenwindowNewmailUnprocessableEntityList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostUiOpenwindowNewmailUnprocessableEntityList ) UnmarshalJSON([]byte) error { return nil }
func ( PostUiOpenwindowNewmailUnprocessableEntityList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostUiOpenwindowNewmailUnprocessableEntityList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostUiOpenwindowNewmailUnprocessableEntityList *PostUiOpenwindowNewmailUnprocessableEntityList
