// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( PostUniverseIdsCorporation ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostUniverseIdsCorporation ) UnmarshalJSON([]byte) error { return nil }
func ( PostUniverseIdsCorporation ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostUniverseIdsCorporation ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostUniverseIdsCorporation *PostUniverseIdsCorporation

func ( PostUniverseIdsCorporationList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostUniverseIdsCorporationList ) UnmarshalJSON([]byte) error { return nil }
func ( PostUniverseIdsCorporationList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostUniverseIdsCorporationList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostUniverseIdsCorporationList *PostUniverseIdsCorporationList
