// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetUniverseCategoriesCategoryIdOk ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseCategoriesCategoryIdOk ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseCategoriesCategoryIdOk ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseCategoriesCategoryIdOk ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseCategoriesCategoryIdOk *GetUniverseCategoriesCategoryIdOk

func ( GetUniverseCategoriesCategoryIdOkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseCategoriesCategoryIdOkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseCategoriesCategoryIdOkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseCategoriesCategoryIdOkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseCategoriesCategoryIdOkList *GetUniverseCategoriesCategoryIdOkList
