// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( PostUniverseIdsCharacter ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostUniverseIdsCharacter ) UnmarshalJSON([]byte) error { return nil }
func ( PostUniverseIdsCharacter ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostUniverseIdsCharacter ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostUniverseIdsCharacter *PostUniverseIdsCharacter

func ( PostUniverseIdsCharacterList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostUniverseIdsCharacterList ) UnmarshalJSON([]byte) error { return nil }
func ( PostUniverseIdsCharacterList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostUniverseIdsCharacterList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostUniverseIdsCharacterList *PostUniverseIdsCharacterList
