// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( PostCharactersCharacterIdContactsError520 ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostCharactersCharacterIdContactsError520 ) UnmarshalJSON([]byte) error { return nil }
func ( PostCharactersCharacterIdContactsError520 ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostCharactersCharacterIdContactsError520 ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostCharactersCharacterIdContactsError520 *PostCharactersCharacterIdContactsError520

func ( PostCharactersCharacterIdContactsError520List ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostCharactersCharacterIdContactsError520List ) UnmarshalJSON([]byte) error { return nil }
func ( PostCharactersCharacterIdContactsError520List ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostCharactersCharacterIdContactsError520List ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostCharactersCharacterIdContactsError520List *PostCharactersCharacterIdContactsError520List
