// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCharactersCharacterIdFittings200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdFittings200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdFittings200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdFittings200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdFittings200Ok *GetCharactersCharacterIdFittings200Ok

func ( GetCharactersCharacterIdFittings200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdFittings200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdFittings200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdFittings200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdFittings200OkList *GetCharactersCharacterIdFittings200OkList
