// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetUniverseConstellationsConstellationIdOk ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseConstellationsConstellationIdOk ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseConstellationsConstellationIdOk ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseConstellationsConstellationIdOk ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseConstellationsConstellationIdOk *GetUniverseConstellationsConstellationIdOk

func ( GetUniverseConstellationsConstellationIdOkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseConstellationsConstellationIdOkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseConstellationsConstellationIdOkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseConstellationsConstellationIdOkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseConstellationsConstellationIdOkList *GetUniverseConstellationsConstellationIdOkList
