// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCharactersCharacterIdMailMailIdNotFound ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdMailMailIdNotFound ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdMailMailIdNotFound ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdMailMailIdNotFound ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdMailMailIdNotFound *GetCharactersCharacterIdMailMailIdNotFound

func ( GetCharactersCharacterIdMailMailIdNotFoundList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdMailMailIdNotFoundList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdMailMailIdNotFoundList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdMailMailIdNotFoundList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdMailMailIdNotFoundList *GetCharactersCharacterIdMailMailIdNotFoundList
