// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCharactersCharacterIdFatigueOk ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdFatigueOk ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdFatigueOk ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdFatigueOk ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdFatigueOk *GetCharactersCharacterIdFatigueOk

func ( GetCharactersCharacterIdFatigueOkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdFatigueOkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdFatigueOkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdFatigueOkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdFatigueOkList *GetCharactersCharacterIdFatigueOkList
