// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCharactersCharacterIdKillmailsRecent200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdKillmailsRecent200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdKillmailsRecent200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdKillmailsRecent200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdKillmailsRecent200Ok *GetCharactersCharacterIdKillmailsRecent200Ok

func ( GetCharactersCharacterIdKillmailsRecent200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdKillmailsRecent200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdKillmailsRecent200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdKillmailsRecent200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdKillmailsRecent200OkList *GetCharactersCharacterIdKillmailsRecent200OkList
