// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetWarsWarIdAggressor ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetWarsWarIdAggressor ) UnmarshalJSON([]byte) error { return nil }
func ( GetWarsWarIdAggressor ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetWarsWarIdAggressor ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetWarsWarIdAggressor *GetWarsWarIdAggressor

func ( GetWarsWarIdAggressorList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetWarsWarIdAggressorList ) UnmarshalJSON([]byte) error { return nil }
func ( GetWarsWarIdAggressorList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetWarsWarIdAggressorList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetWarsWarIdAggressorList *GetWarsWarIdAggressorList
