// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( PostFleetsFleetIdMembersUnprocessableEntity ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostFleetsFleetIdMembersUnprocessableEntity ) UnmarshalJSON([]byte) error { return nil }
func ( PostFleetsFleetIdMembersUnprocessableEntity ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostFleetsFleetIdMembersUnprocessableEntity ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostFleetsFleetIdMembersUnprocessableEntity *PostFleetsFleetIdMembersUnprocessableEntity

func ( PostFleetsFleetIdMembersUnprocessableEntityList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostFleetsFleetIdMembersUnprocessableEntityList ) UnmarshalJSON([]byte) error { return nil }
func ( PostFleetsFleetIdMembersUnprocessableEntityList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostFleetsFleetIdMembersUnprocessableEntityList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostFleetsFleetIdMembersUnprocessableEntityList *PostFleetsFleetIdMembersUnprocessableEntityList
