// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetKillmailsKillmailIdKillmailHashUnprocessableEntity ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetKillmailsKillmailIdKillmailHashUnprocessableEntity ) UnmarshalJSON([]byte) error { return nil }
func ( GetKillmailsKillmailIdKillmailHashUnprocessableEntity ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetKillmailsKillmailIdKillmailHashUnprocessableEntity ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetKillmailsKillmailIdKillmailHashUnprocessableEntity *GetKillmailsKillmailIdKillmailHashUnprocessableEntity

func ( GetKillmailsKillmailIdKillmailHashUnprocessableEntityList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetKillmailsKillmailIdKillmailHashUnprocessableEntityList ) UnmarshalJSON([]byte) error { return nil }
func ( GetKillmailsKillmailIdKillmailHashUnprocessableEntityList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetKillmailsKillmailIdKillmailHashUnprocessableEntityList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetKillmailsKillmailIdKillmailHashUnprocessableEntityList *GetKillmailsKillmailIdKillmailHashUnprocessableEntityList
