// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( PostCharactersCharacterIdFittingsCreated ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostCharactersCharacterIdFittingsCreated ) UnmarshalJSON([]byte) error { return nil }
func ( PostCharactersCharacterIdFittingsCreated ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostCharactersCharacterIdFittingsCreated ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostCharactersCharacterIdFittingsCreated *PostCharactersCharacterIdFittingsCreated

func ( PostCharactersCharacterIdFittingsCreatedList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostCharactersCharacterIdFittingsCreatedList ) UnmarshalJSON([]byte) error { return nil }
func ( PostCharactersCharacterIdFittingsCreatedList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostCharactersCharacterIdFittingsCreatedList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostCharactersCharacterIdFittingsCreatedList *PostCharactersCharacterIdFittingsCreatedList
