// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCorporationsCorporationIdFacilities200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdFacilities200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdFacilities200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdFacilities200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdFacilities200Ok *GetCorporationsCorporationIdFacilities200Ok

func ( GetCorporationsCorporationIdFacilities200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdFacilities200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdFacilities200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdFacilities200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdFacilities200OkList *GetCorporationsCorporationIdFacilities200OkList
