// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( PostCharactersCharacterIdMailMail ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostCharactersCharacterIdMailMail ) UnmarshalJSON([]byte) error { return nil }
func ( PostCharactersCharacterIdMailMail ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostCharactersCharacterIdMailMail ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostCharactersCharacterIdMailMail *PostCharactersCharacterIdMailMail

func ( PostCharactersCharacterIdMailMailList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostCharactersCharacterIdMailMailList ) UnmarshalJSON([]byte) error { return nil }
func ( PostCharactersCharacterIdMailMailList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostCharactersCharacterIdMailMailList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostCharactersCharacterIdMailMailList *PostCharactersCharacterIdMailMailList
