// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetFwLeaderboardsCharactersYesterdayYesterday1 ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFwLeaderboardsCharactersYesterdayYesterday1 ) UnmarshalJSON([]byte) error { return nil }
func ( GetFwLeaderboardsCharactersYesterdayYesterday1 ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFwLeaderboardsCharactersYesterdayYesterday1 ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFwLeaderboardsCharactersYesterdayYesterday1 *GetFwLeaderboardsCharactersYesterdayYesterday1

func ( GetFwLeaderboardsCharactersYesterdayYesterday1List ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFwLeaderboardsCharactersYesterdayYesterday1List ) UnmarshalJSON([]byte) error { return nil }
func ( GetFwLeaderboardsCharactersYesterdayYesterday1List ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFwLeaderboardsCharactersYesterdayYesterday1List ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFwLeaderboardsCharactersYesterdayYesterday1List *GetFwLeaderboardsCharactersYesterdayYesterday1List
