// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCorporationsCorporationIdContractsContractIdBids200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdContractsContractIdBids200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdContractsContractIdBids200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdContractsContractIdBids200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdContractsContractIdBids200Ok *GetCorporationsCorporationIdContractsContractIdBids200Ok

func ( GetCorporationsCorporationIdContractsContractIdBids200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdContractsContractIdBids200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdContractsContractIdBids200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdContractsContractIdBids200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdContractsContractIdBids200OkList *GetCorporationsCorporationIdContractsContractIdBids200OkList
