// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCorporationsCorporationIdFwStatsKills ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdFwStatsKills ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdFwStatsKills ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdFwStatsKills ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdFwStatsKills *GetCorporationsCorporationIdFwStatsKills

func ( GetCorporationsCorporationIdFwStatsKillsList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdFwStatsKillsList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdFwStatsKillsList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdFwStatsKillsList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdFwStatsKillsList *GetCorporationsCorporationIdFwStatsKillsList
