// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetUniverseStationsStationIdOk ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseStationsStationIdOk ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseStationsStationIdOk ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseStationsStationIdOk ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseStationsStationIdOk *GetUniverseStationsStationIdOk

func ( GetUniverseStationsStationIdOkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseStationsStationIdOkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseStationsStationIdOkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseStationsStationIdOkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseStationsStationIdOkList *GetUniverseStationsStationIdOkList
