// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetUniverseStationsStationIdPosition ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseStationsStationIdPosition ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseStationsStationIdPosition ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseStationsStationIdPosition ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseStationsStationIdPosition *GetUniverseStationsStationIdPosition

func ( GetUniverseStationsStationIdPositionList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseStationsStationIdPositionList ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseStationsStationIdPositionList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseStationsStationIdPositionList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseStationsStationIdPositionList *GetUniverseStationsStationIdPositionList
