// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCorporationsCorporationIdAssets200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdAssets200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdAssets200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdAssets200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdAssets200Ok *GetCorporationsCorporationIdAssets200Ok

func ( GetCorporationsCorporationIdAssets200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdAssets200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdAssets200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdAssets200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdAssets200OkList *GetCorporationsCorporationIdAssets200OkList
