// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCharactersCharacterIdAttributesOk ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdAttributesOk ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdAttributesOk ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdAttributesOk ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdAttributesOk *GetCharactersCharacterIdAttributesOk

func ( GetCharactersCharacterIdAttributesOkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdAttributesOkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdAttributesOkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdAttributesOkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdAttributesOkList *GetCharactersCharacterIdAttributesOkList
