// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetFwLeaderboardsLastWeekLastWeek1 ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFwLeaderboardsLastWeekLastWeek1 ) UnmarshalJSON([]byte) error { return nil }
func ( GetFwLeaderboardsLastWeekLastWeek1 ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFwLeaderboardsLastWeekLastWeek1 ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFwLeaderboardsLastWeekLastWeek1 *GetFwLeaderboardsLastWeekLastWeek1

func ( GetFwLeaderboardsLastWeekLastWeek1List ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFwLeaderboardsLastWeekLastWeek1List ) UnmarshalJSON([]byte) error { return nil }
func ( GetFwLeaderboardsLastWeekLastWeek1List ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFwLeaderboardsLastWeekLastWeek1List ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFwLeaderboardsLastWeekLastWeek1List *GetFwLeaderboardsLastWeekLastWeek1List
