// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetFwLeaderboardsCorporationsVictoryPoints ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFwLeaderboardsCorporationsVictoryPoints ) UnmarshalJSON([]byte) error { return nil }
func ( GetFwLeaderboardsCorporationsVictoryPoints ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFwLeaderboardsCorporationsVictoryPoints ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFwLeaderboardsCorporationsVictoryPoints *GetFwLeaderboardsCorporationsVictoryPoints

func ( GetFwLeaderboardsCorporationsVictoryPointsList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFwLeaderboardsCorporationsVictoryPointsList ) UnmarshalJSON([]byte) error { return nil }
func ( GetFwLeaderboardsCorporationsVictoryPointsList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFwLeaderboardsCorporationsVictoryPointsList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFwLeaderboardsCorporationsVictoryPointsList *GetFwLeaderboardsCorporationsVictoryPointsList
