// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetUniverseSystemsSystemIdOk ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseSystemsSystemIdOk ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseSystemsSystemIdOk ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseSystemsSystemIdOk ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseSystemsSystemIdOk *GetUniverseSystemsSystemIdOk

func ( GetUniverseSystemsSystemIdOkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseSystemsSystemIdOkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseSystemsSystemIdOkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseSystemsSystemIdOkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseSystemsSystemIdOkList *GetUniverseSystemsSystemIdOkList
