// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCorporationsCorporationIdRolesHistory200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdRolesHistory200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdRolesHistory200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdRolesHistory200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdRolesHistory200Ok *GetCorporationsCorporationIdRolesHistory200Ok

func ( GetCorporationsCorporationIdRolesHistory200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdRolesHistory200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdRolesHistory200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdRolesHistory200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdRolesHistory200OkList *GetCorporationsCorporationIdRolesHistory200OkList
