// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( PutFleetsFleetIdMembersMemberIdNotFound ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PutFleetsFleetIdMembersMemberIdNotFound ) UnmarshalJSON([]byte) error { return nil }
func ( PutFleetsFleetIdMembersMemberIdNotFound ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PutFleetsFleetIdMembersMemberIdNotFound ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PutFleetsFleetIdMembersMemberIdNotFound *PutFleetsFleetIdMembersMemberIdNotFound

func ( PutFleetsFleetIdMembersMemberIdNotFoundList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PutFleetsFleetIdMembersMemberIdNotFoundList ) UnmarshalJSON([]byte) error { return nil }
func ( PutFleetsFleetIdMembersMemberIdNotFoundList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PutFleetsFleetIdMembersMemberIdNotFoundList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PutFleetsFleetIdMembersMemberIdNotFoundList *PutFleetsFleetIdMembersMemberIdNotFoundList
