// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCharactersCharacterIdIndustryJobs200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdIndustryJobs200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdIndustryJobs200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdIndustryJobs200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdIndustryJobs200Ok *GetCharactersCharacterIdIndustryJobs200Ok

func ( GetCharactersCharacterIdIndustryJobs200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdIndustryJobs200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdIndustryJobs200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdIndustryJobs200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdIndustryJobs200OkList *GetCharactersCharacterIdIndustryJobs200OkList
