// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( PutFleetsFleetIdSquadsSquadIdNotFound ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PutFleetsFleetIdSquadsSquadIdNotFound ) UnmarshalJSON([]byte) error { return nil }
func ( PutFleetsFleetIdSquadsSquadIdNotFound ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PutFleetsFleetIdSquadsSquadIdNotFound ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PutFleetsFleetIdSquadsSquadIdNotFound *PutFleetsFleetIdSquadsSquadIdNotFound

func ( PutFleetsFleetIdSquadsSquadIdNotFoundList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PutFleetsFleetIdSquadsSquadIdNotFoundList ) UnmarshalJSON([]byte) error { return nil }
func ( PutFleetsFleetIdSquadsSquadIdNotFoundList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PutFleetsFleetIdSquadsSquadIdNotFoundList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PutFleetsFleetIdSquadsSquadIdNotFoundList *PutFleetsFleetIdSquadsSquadIdNotFoundList
