// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetUniverseTypesTypeIdNotFound ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseTypesTypeIdNotFound ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseTypesTypeIdNotFound ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseTypesTypeIdNotFound ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseTypesTypeIdNotFound *GetUniverseTypesTypeIdNotFound

func ( GetUniverseTypesTypeIdNotFoundList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseTypesTypeIdNotFoundList ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseTypesTypeIdNotFoundList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseTypesTypeIdNotFoundList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseTypesTypeIdNotFoundList *GetUniverseTypesTypeIdNotFoundList
