// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetUniverseConstellationsConstellationIdNotFound ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseConstellationsConstellationIdNotFound ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseConstellationsConstellationIdNotFound ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseConstellationsConstellationIdNotFound ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseConstellationsConstellationIdNotFound *GetUniverseConstellationsConstellationIdNotFound

func ( GetUniverseConstellationsConstellationIdNotFoundList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseConstellationsConstellationIdNotFoundList ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseConstellationsConstellationIdNotFoundList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseConstellationsConstellationIdNotFoundList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseConstellationsConstellationIdNotFoundList *GetUniverseConstellationsConstellationIdNotFoundList
