// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetAlliancesAllianceIdOk ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetAlliancesAllianceIdOk ) UnmarshalJSON([]byte) error { return nil }
func ( GetAlliancesAllianceIdOk ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetAlliancesAllianceIdOk ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetAlliancesAllianceIdOk *GetAlliancesAllianceIdOk

func ( GetAlliancesAllianceIdOkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetAlliancesAllianceIdOkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetAlliancesAllianceIdOkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetAlliancesAllianceIdOkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetAlliancesAllianceIdOkList *GetAlliancesAllianceIdOkList
