// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCharactersCharacterIdCalendarEventIdAttendees200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdCalendarEventIdAttendees200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdCalendarEventIdAttendees200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdCalendarEventIdAttendees200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdCalendarEventIdAttendees200Ok *GetCharactersCharacterIdCalendarEventIdAttendees200Ok

func ( GetCharactersCharacterIdCalendarEventIdAttendees200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdCalendarEventIdAttendees200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdCalendarEventIdAttendees200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdCalendarEventIdAttendees200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdCalendarEventIdAttendees200OkList *GetCharactersCharacterIdCalendarEventIdAttendees200OkList
