// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetKillmailsKillmailIdKillmailHashItemsItem ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetKillmailsKillmailIdKillmailHashItemsItem ) UnmarshalJSON([]byte) error { return nil }
func ( GetKillmailsKillmailIdKillmailHashItemsItem ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetKillmailsKillmailIdKillmailHashItemsItem ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetKillmailsKillmailIdKillmailHashItemsItem *GetKillmailsKillmailIdKillmailHashItemsItem

func ( GetKillmailsKillmailIdKillmailHashItemsItemList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetKillmailsKillmailIdKillmailHashItemsItemList ) UnmarshalJSON([]byte) error { return nil }
func ( GetKillmailsKillmailIdKillmailHashItemsItemList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetKillmailsKillmailIdKillmailHashItemsItemList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetKillmailsKillmailIdKillmailHashItemsItemList *GetKillmailsKillmailIdKillmailHashItemsItemList
