// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCorporationsCorporationIdRoles200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdRoles200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdRoles200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdRoles200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdRoles200Ok *GetCorporationsCorporationIdRoles200Ok

func ( GetCorporationsCorporationIdRoles200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdRoles200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdRoles200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdRoles200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdRoles200OkList *GetCorporationsCorporationIdRoles200OkList
