// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCharactersCharacterIdSkillsSkill ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdSkillsSkill ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdSkillsSkill ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdSkillsSkill ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdSkillsSkill *GetCharactersCharacterIdSkillsSkill

func ( GetCharactersCharacterIdSkillsSkillList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdSkillsSkillList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdSkillsSkillList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdSkillsSkillList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdSkillsSkillList *GetCharactersCharacterIdSkillsSkillList
