// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetFwLeaderboardsActiveTotalActiveTotal ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFwLeaderboardsActiveTotalActiveTotal ) UnmarshalJSON([]byte) error { return nil }
func ( GetFwLeaderboardsActiveTotalActiveTotal ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFwLeaderboardsActiveTotalActiveTotal ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFwLeaderboardsActiveTotalActiveTotal *GetFwLeaderboardsActiveTotalActiveTotal

func ( GetFwLeaderboardsActiveTotalActiveTotalList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFwLeaderboardsActiveTotalActiveTotalList ) UnmarshalJSON([]byte) error { return nil }
func ( GetFwLeaderboardsActiveTotalActiveTotalList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFwLeaderboardsActiveTotalActiveTotalList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFwLeaderboardsActiveTotalActiveTotalList *GetFwLeaderboardsActiveTotalActiveTotalList
