// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCharactersCharacterIdShipOk ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdShipOk ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdShipOk ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdShipOk ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdShipOk *GetCharactersCharacterIdShipOk

func ( GetCharactersCharacterIdShipOkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdShipOkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdShipOkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdShipOkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdShipOkList *GetCharactersCharacterIdShipOkList
