// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCorporationsCorporationIdContractsContractIdBidsNotFound ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdContractsContractIdBidsNotFound ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdContractsContractIdBidsNotFound ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdContractsContractIdBidsNotFound ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdContractsContractIdBidsNotFound *GetCorporationsCorporationIdContractsContractIdBidsNotFound

func ( GetCorporationsCorporationIdContractsContractIdBidsNotFoundList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdContractsContractIdBidsNotFoundList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdContractsContractIdBidsNotFoundList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdContractsContractIdBidsNotFoundList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdContractsContractIdBidsNotFoundList *GetCorporationsCorporationIdContractsContractIdBidsNotFoundList
