// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( PutFleetsFleetIdWingsWingIdNotFound ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PutFleetsFleetIdWingsWingIdNotFound ) UnmarshalJSON([]byte) error { return nil }
func ( PutFleetsFleetIdWingsWingIdNotFound ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PutFleetsFleetIdWingsWingIdNotFound ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PutFleetsFleetIdWingsWingIdNotFound *PutFleetsFleetIdWingsWingIdNotFound

func ( PutFleetsFleetIdWingsWingIdNotFoundList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PutFleetsFleetIdWingsWingIdNotFoundList ) UnmarshalJSON([]byte) error { return nil }
func ( PutFleetsFleetIdWingsWingIdNotFoundList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PutFleetsFleetIdWingsWingIdNotFoundList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PutFleetsFleetIdWingsWingIdNotFoundList *PutFleetsFleetIdWingsWingIdNotFoundList
