// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCorporationsCorporationIdStarbasesStarbaseIdOk ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdStarbasesStarbaseIdOk ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdStarbasesStarbaseIdOk ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdStarbasesStarbaseIdOk ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdStarbasesStarbaseIdOk *GetCorporationsCorporationIdStarbasesStarbaseIdOk

func ( GetCorporationsCorporationIdStarbasesStarbaseIdOkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdStarbasesStarbaseIdOkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdStarbasesStarbaseIdOkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdStarbasesStarbaseIdOkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdStarbasesStarbaseIdOkList *GetCorporationsCorporationIdStarbasesStarbaseIdOkList
