// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetUniverseStarsStarIdOk ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseStarsStarIdOk ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseStarsStarIdOk ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseStarsStarIdOk ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseStarsStarIdOk *GetUniverseStarsStarIdOk

func ( GetUniverseStarsStarIdOkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseStarsStarIdOkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseStarsStarIdOkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseStarsStarIdOkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseStarsStarIdOkList *GetUniverseStarsStarIdOkList
