// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCharactersCharacterIdContacts200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdContacts200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdContacts200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdContacts200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdContacts200Ok *GetCharactersCharacterIdContacts200Ok

func ( GetCharactersCharacterIdContacts200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdContacts200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdContacts200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdContacts200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdContacts200OkList *GetCharactersCharacterIdContacts200OkList
