// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCharactersCharacterIdLocationOk ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdLocationOk ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdLocationOk ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdLocationOk ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdLocationOk *GetCharactersCharacterIdLocationOk

func ( GetCharactersCharacterIdLocationOkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdLocationOkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdLocationOkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdLocationOkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdLocationOkList *GetCharactersCharacterIdLocationOkList
