// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCorporationsCorporationIdStandings200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdStandings200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdStandings200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdStandings200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdStandings200Ok *GetCorporationsCorporationIdStandings200Ok

func ( GetCorporationsCorporationIdStandings200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdStandings200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdStandings200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdStandings200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdStandings200OkList *GetCorporationsCorporationIdStandings200OkList
