// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetUniverseMoonsMoonIdPosition ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseMoonsMoonIdPosition ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseMoonsMoonIdPosition ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseMoonsMoonIdPosition ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseMoonsMoonIdPosition *GetUniverseMoonsMoonIdPosition

func ( GetUniverseMoonsMoonIdPositionList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseMoonsMoonIdPositionList ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseMoonsMoonIdPositionList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseMoonsMoonIdPositionList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseMoonsMoonIdPositionList *GetUniverseMoonsMoonIdPositionList
