// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetFleetsFleetIdWingsSquad ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFleetsFleetIdWingsSquad ) UnmarshalJSON([]byte) error { return nil }
func ( GetFleetsFleetIdWingsSquad ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFleetsFleetIdWingsSquad ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFleetsFleetIdWingsSquad *GetFleetsFleetIdWingsSquad

func ( GetFleetsFleetIdWingsSquadList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFleetsFleetIdWingsSquadList ) UnmarshalJSON([]byte) error { return nil }
func ( GetFleetsFleetIdWingsSquadList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFleetsFleetIdWingsSquadList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFleetsFleetIdWingsSquadList *GetFleetsFleetIdWingsSquadList
