// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetFleetsFleetIdMembers200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFleetsFleetIdMembers200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetFleetsFleetIdMembers200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFleetsFleetIdMembers200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFleetsFleetIdMembers200Ok *GetFleetsFleetIdMembers200Ok

func ( GetFleetsFleetIdMembers200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFleetsFleetIdMembers200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetFleetsFleetIdMembers200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFleetsFleetIdMembers200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFleetsFleetIdMembers200OkList *GetFleetsFleetIdMembers200OkList
