// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCorporationsCorporationIdMembertracking200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdMembertracking200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdMembertracking200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdMembertracking200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdMembertracking200Ok *GetCorporationsCorporationIdMembertracking200Ok

func ( GetCorporationsCorporationIdMembertracking200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdMembertracking200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdMembertracking200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdMembertracking200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdMembertracking200OkList *GetCorporationsCorporationIdMembertracking200OkList
