// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( PostUniverseIdsRegion ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostUniverseIdsRegion ) UnmarshalJSON([]byte) error { return nil }
func ( PostUniverseIdsRegion ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostUniverseIdsRegion ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostUniverseIdsRegion *PostUniverseIdsRegion

func ( PostUniverseIdsRegionList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostUniverseIdsRegionList ) UnmarshalJSON([]byte) error { return nil }
func ( PostUniverseIdsRegionList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostUniverseIdsRegionList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostUniverseIdsRegionList *PostUniverseIdsRegionList
