// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetDogmaEffectsEffectIdModifier ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetDogmaEffectsEffectIdModifier ) UnmarshalJSON([]byte) error { return nil }
func ( GetDogmaEffectsEffectIdModifier ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetDogmaEffectsEffectIdModifier ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetDogmaEffectsEffectIdModifier *GetDogmaEffectsEffectIdModifier

func ( GetDogmaEffectsEffectIdModifierList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetDogmaEffectsEffectIdModifierList ) UnmarshalJSON([]byte) error { return nil }
func ( GetDogmaEffectsEffectIdModifierList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetDogmaEffectsEffectIdModifierList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetDogmaEffectsEffectIdModifierList *GetDogmaEffectsEffectIdModifierList
