// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetFwLeaderboardsCorporationsLastWeekLastWeek1 ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFwLeaderboardsCorporationsLastWeekLastWeek1 ) UnmarshalJSON([]byte) error { return nil }
func ( GetFwLeaderboardsCorporationsLastWeekLastWeek1 ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFwLeaderboardsCorporationsLastWeekLastWeek1 ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFwLeaderboardsCorporationsLastWeekLastWeek1 *GetFwLeaderboardsCorporationsLastWeekLastWeek1

func ( GetFwLeaderboardsCorporationsLastWeekLastWeek1List ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFwLeaderboardsCorporationsLastWeekLastWeek1List ) UnmarshalJSON([]byte) error { return nil }
func ( GetFwLeaderboardsCorporationsLastWeekLastWeek1List ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFwLeaderboardsCorporationsLastWeekLastWeek1List ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFwLeaderboardsCorporationsLastWeekLastWeek1List *GetFwLeaderboardsCorporationsLastWeekLastWeek1List
