// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetFwLeaderboardsCharactersYesterdayYesterday ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFwLeaderboardsCharactersYesterdayYesterday ) UnmarshalJSON([]byte) error { return nil }
func ( GetFwLeaderboardsCharactersYesterdayYesterday ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFwLeaderboardsCharactersYesterdayYesterday ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFwLeaderboardsCharactersYesterdayYesterday *GetFwLeaderboardsCharactersYesterdayYesterday

func ( GetFwLeaderboardsCharactersYesterdayYesterdayList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFwLeaderboardsCharactersYesterdayYesterdayList ) UnmarshalJSON([]byte) error { return nil }
func ( GetFwLeaderboardsCharactersYesterdayYesterdayList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFwLeaderboardsCharactersYesterdayYesterdayList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFwLeaderboardsCharactersYesterdayYesterdayList *GetFwLeaderboardsCharactersYesterdayYesterdayList
