// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( DeleteCharactersCharacterIdMailLabelsLabelIdUnprocessableEntity ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* DeleteCharactersCharacterIdMailLabelsLabelIdUnprocessableEntity ) UnmarshalJSON([]byte) error { return nil }
func ( DeleteCharactersCharacterIdMailLabelsLabelIdUnprocessableEntity ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* DeleteCharactersCharacterIdMailLabelsLabelIdUnprocessableEntity ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_DeleteCharactersCharacterIdMailLabelsLabelIdUnprocessableEntity *DeleteCharactersCharacterIdMailLabelsLabelIdUnprocessableEntity

func ( DeleteCharactersCharacterIdMailLabelsLabelIdUnprocessableEntityList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* DeleteCharactersCharacterIdMailLabelsLabelIdUnprocessableEntityList ) UnmarshalJSON([]byte) error { return nil }
func ( DeleteCharactersCharacterIdMailLabelsLabelIdUnprocessableEntityList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* DeleteCharactersCharacterIdMailLabelsLabelIdUnprocessableEntityList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_DeleteCharactersCharacterIdMailLabelsLabelIdUnprocessableEntityList *DeleteCharactersCharacterIdMailLabelsLabelIdUnprocessableEntityList
