// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( ServiceUnavailable ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* ServiceUnavailable ) UnmarshalJSON([]byte) error { return nil }
func ( ServiceUnavailable ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* ServiceUnavailable ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ServiceUnavailable *ServiceUnavailable

func ( ServiceUnavailableList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* ServiceUnavailableList ) UnmarshalJSON([]byte) error { return nil }
func ( ServiceUnavailableList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* ServiceUnavailableList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ServiceUnavailableList *ServiceUnavailableList
