// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( PostCharactersCharacterIdMailError520 ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostCharactersCharacterIdMailError520 ) UnmarshalJSON([]byte) error { return nil }
func ( PostCharactersCharacterIdMailError520 ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostCharactersCharacterIdMailError520 ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostCharactersCharacterIdMailError520 *PostCharactersCharacterIdMailError520

func ( PostCharactersCharacterIdMailError520List ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostCharactersCharacterIdMailError520List ) UnmarshalJSON([]byte) error { return nil }
func ( PostCharactersCharacterIdMailError520List ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostCharactersCharacterIdMailError520List ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostCharactersCharacterIdMailError520List *PostCharactersCharacterIdMailError520List
