// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetMarketsRegionIdOrders200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetMarketsRegionIdOrders200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetMarketsRegionIdOrders200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetMarketsRegionIdOrders200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetMarketsRegionIdOrders200Ok *GetMarketsRegionIdOrders200Ok

func ( GetMarketsRegionIdOrders200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetMarketsRegionIdOrders200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetMarketsRegionIdOrders200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetMarketsRegionIdOrders200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetMarketsRegionIdOrders200OkList *GetMarketsRegionIdOrders200OkList
