// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetLoyaltyStoresCorporationIdOffers200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetLoyaltyStoresCorporationIdOffers200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetLoyaltyStoresCorporationIdOffers200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetLoyaltyStoresCorporationIdOffers200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetLoyaltyStoresCorporationIdOffers200Ok *GetLoyaltyStoresCorporationIdOffers200Ok

func ( GetLoyaltyStoresCorporationIdOffers200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetLoyaltyStoresCorporationIdOffers200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetLoyaltyStoresCorporationIdOffers200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetLoyaltyStoresCorporationIdOffers200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetLoyaltyStoresCorporationIdOffers200OkList *GetLoyaltyStoresCorporationIdOffers200OkList
