// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetUniverseSystemJumps200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseSystemJumps200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseSystemJumps200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseSystemJumps200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseSystemJumps200Ok *GetUniverseSystemJumps200Ok

func ( GetUniverseSystemJumps200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseSystemJumps200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseSystemJumps200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseSystemJumps200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseSystemJumps200OkList *GetUniverseSystemJumps200OkList
