// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetContractsPublicItemsContractIdNotFound ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetContractsPublicItemsContractIdNotFound ) UnmarshalJSON([]byte) error { return nil }
func ( GetContractsPublicItemsContractIdNotFound ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetContractsPublicItemsContractIdNotFound ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetContractsPublicItemsContractIdNotFound *GetContractsPublicItemsContractIdNotFound

func ( GetContractsPublicItemsContractIdNotFoundList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetContractsPublicItemsContractIdNotFoundList ) UnmarshalJSON([]byte) error { return nil }
func ( GetContractsPublicItemsContractIdNotFoundList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetContractsPublicItemsContractIdNotFoundList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetContractsPublicItemsContractIdNotFoundList *GetContractsPublicItemsContractIdNotFoundList
