// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCharactersCharacterIdAssetsNotFound ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdAssetsNotFound ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdAssetsNotFound ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdAssetsNotFound ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdAssetsNotFound *GetCharactersCharacterIdAssetsNotFound

func ( GetCharactersCharacterIdAssetsNotFoundList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdAssetsNotFoundList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdAssetsNotFoundList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdAssetsNotFoundList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdAssetsNotFoundList *GetCharactersCharacterIdAssetsNotFoundList
