// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetFwLeaderboardsKills ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFwLeaderboardsKills ) UnmarshalJSON([]byte) error { return nil }
func ( GetFwLeaderboardsKills ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFwLeaderboardsKills ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFwLeaderboardsKills *GetFwLeaderboardsKills

func ( GetFwLeaderboardsKillsList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFwLeaderboardsKillsList ) UnmarshalJSON([]byte) error { return nil }
func ( GetFwLeaderboardsKillsList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFwLeaderboardsKillsList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFwLeaderboardsKillsList *GetFwLeaderboardsKillsList
