// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetFwLeaderboardsCharactersOk ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFwLeaderboardsCharactersOk ) UnmarshalJSON([]byte) error { return nil }
func ( GetFwLeaderboardsCharactersOk ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFwLeaderboardsCharactersOk ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFwLeaderboardsCharactersOk *GetFwLeaderboardsCharactersOk

func ( GetFwLeaderboardsCharactersOkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFwLeaderboardsCharactersOkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetFwLeaderboardsCharactersOkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFwLeaderboardsCharactersOkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFwLeaderboardsCharactersOkList *GetFwLeaderboardsCharactersOkList
