// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCorporationCorporationIdMiningObserversObserverId200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationCorporationIdMiningObserversObserverId200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationCorporationIdMiningObserversObserverId200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationCorporationIdMiningObserversObserverId200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationCorporationIdMiningObserversObserverId200Ok *GetCorporationCorporationIdMiningObserversObserverId200Ok

func ( GetCorporationCorporationIdMiningObserversObserverId200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationCorporationIdMiningObserversObserverId200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationCorporationIdMiningObserversObserverId200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationCorporationIdMiningObserversObserverId200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationCorporationIdMiningObserversObserverId200OkList *GetCorporationCorporationIdMiningObserversObserverId200OkList
