// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetFleetsFleetIdWingsNotFound ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFleetsFleetIdWingsNotFound ) UnmarshalJSON([]byte) error { return nil }
func ( GetFleetsFleetIdWingsNotFound ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFleetsFleetIdWingsNotFound ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFleetsFleetIdWingsNotFound *GetFleetsFleetIdWingsNotFound

func ( GetFleetsFleetIdWingsNotFoundList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFleetsFleetIdWingsNotFoundList ) UnmarshalJSON([]byte) error { return nil }
func ( GetFleetsFleetIdWingsNotFoundList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFleetsFleetIdWingsNotFoundList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFleetsFleetIdWingsNotFoundList *GetFleetsFleetIdWingsNotFoundList
