// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCharactersCharacterIdMedalsGraphic ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdMedalsGraphic ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdMedalsGraphic ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdMedalsGraphic ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdMedalsGraphic *GetCharactersCharacterIdMedalsGraphic

func ( GetCharactersCharacterIdMedalsGraphicList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdMedalsGraphicList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdMedalsGraphicList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdMedalsGraphicList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdMedalsGraphicList *GetCharactersCharacterIdMedalsGraphicList
