// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCharactersCharacterIdBookmarksCoordinates ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdBookmarksCoordinates ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdBookmarksCoordinates ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdBookmarksCoordinates ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdBookmarksCoordinates *GetCharactersCharacterIdBookmarksCoordinates

func ( GetCharactersCharacterIdBookmarksCoordinatesList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdBookmarksCoordinatesList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdBookmarksCoordinatesList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdBookmarksCoordinatesList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdBookmarksCoordinatesList *GetCharactersCharacterIdBookmarksCoordinatesList
