// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCharactersCharacterIdMailMailIdOk ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdMailMailIdOk ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdMailMailIdOk ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdMailMailIdOk ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdMailMailIdOk *GetCharactersCharacterIdMailMailIdOk

func ( GetCharactersCharacterIdMailMailIdOkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdMailMailIdOkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdMailMailIdOkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdMailMailIdOkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdMailMailIdOkList *GetCharactersCharacterIdMailMailIdOkList
