// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetUniverseAsteroidBeltsAsteroidBeltIdNotFound ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseAsteroidBeltsAsteroidBeltIdNotFound ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseAsteroidBeltsAsteroidBeltIdNotFound ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseAsteroidBeltsAsteroidBeltIdNotFound ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseAsteroidBeltsAsteroidBeltIdNotFound *GetUniverseAsteroidBeltsAsteroidBeltIdNotFound

func ( GetUniverseAsteroidBeltsAsteroidBeltIdNotFoundList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseAsteroidBeltsAsteroidBeltIdNotFoundList ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseAsteroidBeltsAsteroidBeltIdNotFoundList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseAsteroidBeltsAsteroidBeltIdNotFoundList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseAsteroidBeltsAsteroidBeltIdNotFoundList *GetUniverseAsteroidBeltsAsteroidBeltIdNotFoundList
