// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCharactersCharacterIdWalletTransactions200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdWalletTransactions200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdWalletTransactions200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdWalletTransactions200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdWalletTransactions200Ok *GetCharactersCharacterIdWalletTransactions200Ok

func ( GetCharactersCharacterIdWalletTransactions200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdWalletTransactions200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdWalletTransactions200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdWalletTransactions200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdWalletTransactions200OkList *GetCharactersCharacterIdWalletTransactions200OkList
