// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( PostUniverseNames200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostUniverseNames200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( PostUniverseNames200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostUniverseNames200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostUniverseNames200Ok *PostUniverseNames200Ok

func ( PostUniverseNames200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostUniverseNames200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( PostUniverseNames200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostUniverseNames200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostUniverseNames200OkList *PostUniverseNames200OkList
