// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCharactersCharacterIdMailLabelsLabel ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdMailLabelsLabel ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdMailLabelsLabel ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdMailLabelsLabel ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdMailLabelsLabel *GetCharactersCharacterIdMailLabelsLabel

func ( GetCharactersCharacterIdMailLabelsLabelList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdMailLabelsLabelList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdMailLabelsLabelList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdMailLabelsLabelList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdMailLabelsLabelList *GetCharactersCharacterIdMailLabelsLabelList
