// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetFwLeaderboardsCharactersVictoryPoints ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFwLeaderboardsCharactersVictoryPoints ) UnmarshalJSON([]byte) error { return nil }
func ( GetFwLeaderboardsCharactersVictoryPoints ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFwLeaderboardsCharactersVictoryPoints ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFwLeaderboardsCharactersVictoryPoints *GetFwLeaderboardsCharactersVictoryPoints

func ( GetFwLeaderboardsCharactersVictoryPointsList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFwLeaderboardsCharactersVictoryPointsList ) UnmarshalJSON([]byte) error { return nil }
func ( GetFwLeaderboardsCharactersVictoryPointsList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFwLeaderboardsCharactersVictoryPointsList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFwLeaderboardsCharactersVictoryPointsList *GetFwLeaderboardsCharactersVictoryPointsList
