// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetUniverseSystemsSystemIdPlanet ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseSystemsSystemIdPlanet ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseSystemsSystemIdPlanet ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseSystemsSystemIdPlanet ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseSystemsSystemIdPlanet *GetUniverseSystemsSystemIdPlanet

func ( GetUniverseSystemsSystemIdPlanetList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseSystemsSystemIdPlanetList ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseSystemsSystemIdPlanetList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseSystemsSystemIdPlanetList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseSystemsSystemIdPlanetList *GetUniverseSystemsSystemIdPlanetList
