// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( PostCorporationsCorporationIdAssetsLocationsPosition ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostCorporationsCorporationIdAssetsLocationsPosition ) UnmarshalJSON([]byte) error { return nil }
func ( PostCorporationsCorporationIdAssetsLocationsPosition ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostCorporationsCorporationIdAssetsLocationsPosition ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostCorporationsCorporationIdAssetsLocationsPosition *PostCorporationsCorporationIdAssetsLocationsPosition

func ( PostCorporationsCorporationIdAssetsLocationsPositionList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostCorporationsCorporationIdAssetsLocationsPositionList ) UnmarshalJSON([]byte) error { return nil }
func ( PostCorporationsCorporationIdAssetsLocationsPositionList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostCorporationsCorporationIdAssetsLocationsPositionList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostCorporationsCorporationIdAssetsLocationsPositionList *PostCorporationsCorporationIdAssetsLocationsPositionList
