// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCharactersCharacterIdContractsContractIdBids200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdContractsContractIdBids200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdContractsContractIdBids200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdContractsContractIdBids200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdContractsContractIdBids200Ok *GetCharactersCharacterIdContractsContractIdBids200Ok

func ( GetCharactersCharacterIdContractsContractIdBids200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdContractsContractIdBids200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdContractsContractIdBids200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdContractsContractIdBids200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdContractsContractIdBids200OkList *GetCharactersCharacterIdContractsContractIdBids200OkList
