// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetFwLeaderboardsCharactersLastWeekLastWeek1 ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFwLeaderboardsCharactersLastWeekLastWeek1 ) UnmarshalJSON([]byte) error { return nil }
func ( GetFwLeaderboardsCharactersLastWeekLastWeek1 ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFwLeaderboardsCharactersLastWeekLastWeek1 ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFwLeaderboardsCharactersLastWeekLastWeek1 *GetFwLeaderboardsCharactersLastWeekLastWeek1

func ( GetFwLeaderboardsCharactersLastWeekLastWeek1List ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFwLeaderboardsCharactersLastWeekLastWeek1List ) UnmarshalJSON([]byte) error { return nil }
func ( GetFwLeaderboardsCharactersLastWeekLastWeek1List ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFwLeaderboardsCharactersLastWeekLastWeek1List ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFwLeaderboardsCharactersLastWeekLastWeek1List *GetFwLeaderboardsCharactersLastWeekLastWeek1List
