// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetMarketsRegionIdOrdersUnprocessableEntity ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetMarketsRegionIdOrdersUnprocessableEntity ) UnmarshalJSON([]byte) error { return nil }
func ( GetMarketsRegionIdOrdersUnprocessableEntity ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetMarketsRegionIdOrdersUnprocessableEntity ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetMarketsRegionIdOrdersUnprocessableEntity *GetMarketsRegionIdOrdersUnprocessableEntity

func ( GetMarketsRegionIdOrdersUnprocessableEntityList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetMarketsRegionIdOrdersUnprocessableEntityList ) UnmarshalJSON([]byte) error { return nil }
func ( GetMarketsRegionIdOrdersUnprocessableEntityList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetMarketsRegionIdOrdersUnprocessableEntityList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetMarketsRegionIdOrdersUnprocessableEntityList *GetMarketsRegionIdOrdersUnprocessableEntityList
