// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetUniverseBloodlines200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseBloodlines200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseBloodlines200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseBloodlines200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseBloodlines200Ok *GetUniverseBloodlines200Ok

func ( GetUniverseBloodlines200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseBloodlines200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseBloodlines200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseBloodlines200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseBloodlines200OkList *GetUniverseBloodlines200OkList
