// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( Unauthorized ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Unauthorized ) UnmarshalJSON([]byte) error { return nil }
func ( Unauthorized ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Unauthorized ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Unauthorized *Unauthorized

func ( UnauthorizedList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* UnauthorizedList ) UnmarshalJSON([]byte) error { return nil }
func ( UnauthorizedList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* UnauthorizedList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_UnauthorizedList *UnauthorizedList
