// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCorporationsCorporationIdBlueprints200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdBlueprints200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdBlueprints200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdBlueprints200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdBlueprints200Ok *GetCorporationsCorporationIdBlueprints200Ok

func ( GetCorporationsCorporationIdBlueprints200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdBlueprints200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdBlueprints200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdBlueprints200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdBlueprints200OkList *GetCorporationsCorporationIdBlueprints200OkList
