// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetSovereigntyStructures200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetSovereigntyStructures200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetSovereigntyStructures200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetSovereigntyStructures200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetSovereigntyStructures200Ok *GetSovereigntyStructures200Ok

func ( GetSovereigntyStructures200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetSovereigntyStructures200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetSovereigntyStructures200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetSovereigntyStructures200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetSovereigntyStructures200OkList *GetSovereigntyStructures200OkList
