// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( PostUniverseIdsAlliance ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostUniverseIdsAlliance ) UnmarshalJSON([]byte) error { return nil }
func ( PostUniverseIdsAlliance ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostUniverseIdsAlliance ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostUniverseIdsAlliance *PostUniverseIdsAlliance

func ( PostUniverseIdsAllianceList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostUniverseIdsAllianceList ) UnmarshalJSON([]byte) error { return nil }
func ( PostUniverseIdsAllianceList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostUniverseIdsAllianceList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostUniverseIdsAllianceList *PostUniverseIdsAllianceList
