// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetMarketsRegionIdHistoryError520 ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetMarketsRegionIdHistoryError520 ) UnmarshalJSON([]byte) error { return nil }
func ( GetMarketsRegionIdHistoryError520 ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetMarketsRegionIdHistoryError520 ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetMarketsRegionIdHistoryError520 *GetMarketsRegionIdHistoryError520

func ( GetMarketsRegionIdHistoryError520List ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetMarketsRegionIdHistoryError520List ) UnmarshalJSON([]byte) error { return nil }
func ( GetMarketsRegionIdHistoryError520List ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetMarketsRegionIdHistoryError520List ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetMarketsRegionIdHistoryError520List *GetMarketsRegionIdHistoryError520List
