// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCorporationsCorporationIdContractsContractIdItemsNotFound ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdContractsContractIdItemsNotFound ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdContractsContractIdItemsNotFound ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdContractsContractIdItemsNotFound ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdContractsContractIdItemsNotFound *GetCorporationsCorporationIdContractsContractIdItemsNotFound

func ( GetCorporationsCorporationIdContractsContractIdItemsNotFoundList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdContractsContractIdItemsNotFoundList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdContractsContractIdItemsNotFoundList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdContractsContractIdItemsNotFoundList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdContractsContractIdItemsNotFoundList *GetCorporationsCorporationIdContractsContractIdItemsNotFoundList
