// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCorporationsCorporationIdOrdersHistory200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdOrdersHistory200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdOrdersHistory200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdOrdersHistory200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdOrdersHistory200Ok *GetCorporationsCorporationIdOrdersHistory200Ok

func ( GetCorporationsCorporationIdOrdersHistory200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdOrdersHistory200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdOrdersHistory200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdOrdersHistory200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdOrdersHistory200OkList *GetCorporationsCorporationIdOrdersHistory200OkList
