// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( PostUniverseIdsOk ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostUniverseIdsOk ) UnmarshalJSON([]byte) error { return nil }
func ( PostUniverseIdsOk ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostUniverseIdsOk ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostUniverseIdsOk *PostUniverseIdsOk

func ( PostUniverseIdsOkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostUniverseIdsOkList ) UnmarshalJSON([]byte) error { return nil }
func ( PostUniverseIdsOkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostUniverseIdsOkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostUniverseIdsOkList *PostUniverseIdsOkList
