// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( PostCharactersCharacterIdFittingsFitting ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostCharactersCharacterIdFittingsFitting ) UnmarshalJSON([]byte) error { return nil }
func ( PostCharactersCharacterIdFittingsFitting ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostCharactersCharacterIdFittingsFitting ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostCharactersCharacterIdFittingsFitting *PostCharactersCharacterIdFittingsFitting

func ( PostCharactersCharacterIdFittingsFittingList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostCharactersCharacterIdFittingsFittingList ) UnmarshalJSON([]byte) error { return nil }
func ( PostCharactersCharacterIdFittingsFittingList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostCharactersCharacterIdFittingsFittingList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostCharactersCharacterIdFittingsFittingList *PostCharactersCharacterIdFittingsFittingList
