// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetFwLeaderboardsCorporationsActiveTotalActiveTotal1 ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFwLeaderboardsCorporationsActiveTotalActiveTotal1 ) UnmarshalJSON([]byte) error { return nil }
func ( GetFwLeaderboardsCorporationsActiveTotalActiveTotal1 ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFwLeaderboardsCorporationsActiveTotalActiveTotal1 ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFwLeaderboardsCorporationsActiveTotalActiveTotal1 *GetFwLeaderboardsCorporationsActiveTotalActiveTotal1

func ( GetFwLeaderboardsCorporationsActiveTotalActiveTotal1List ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFwLeaderboardsCorporationsActiveTotalActiveTotal1List ) UnmarshalJSON([]byte) error { return nil }
func ( GetFwLeaderboardsCorporationsActiveTotalActiveTotal1List ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFwLeaderboardsCorporationsActiveTotalActiveTotal1List ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFwLeaderboardsCorporationsActiveTotalActiveTotal1List *GetFwLeaderboardsCorporationsActiveTotalActiveTotal1List
