// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCharactersCharacterIdPlanetsPlanetIdFactoryDetails ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdPlanetsPlanetIdFactoryDetails ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdPlanetsPlanetIdFactoryDetails ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdPlanetsPlanetIdFactoryDetails ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdPlanetsPlanetIdFactoryDetails *GetCharactersCharacterIdPlanetsPlanetIdFactoryDetails

func ( GetCharactersCharacterIdPlanetsPlanetIdFactoryDetailsList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdPlanetsPlanetIdFactoryDetailsList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdPlanetsPlanetIdFactoryDetailsList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdPlanetsPlanetIdFactoryDetailsList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdPlanetsPlanetIdFactoryDetailsList *GetCharactersCharacterIdPlanetsPlanetIdFactoryDetailsList
