// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetDogmaDynamicItemsTypeIdItemIdNotFound ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetDogmaDynamicItemsTypeIdItemIdNotFound ) UnmarshalJSON([]byte) error { return nil }
func ( GetDogmaDynamicItemsTypeIdItemIdNotFound ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetDogmaDynamicItemsTypeIdItemIdNotFound ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetDogmaDynamicItemsTypeIdItemIdNotFound *GetDogmaDynamicItemsTypeIdItemIdNotFound

func ( GetDogmaDynamicItemsTypeIdItemIdNotFoundList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetDogmaDynamicItemsTypeIdItemIdNotFoundList ) UnmarshalJSON([]byte) error { return nil }
func ( GetDogmaDynamicItemsTypeIdItemIdNotFoundList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetDogmaDynamicItemsTypeIdItemIdNotFoundList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetDogmaDynamicItemsTypeIdItemIdNotFoundList *GetDogmaDynamicItemsTypeIdItemIdNotFoundList
