// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetDogmaDynamicItemsTypeIdItemIdOk ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetDogmaDynamicItemsTypeIdItemIdOk ) UnmarshalJSON([]byte) error { return nil }
func ( GetDogmaDynamicItemsTypeIdItemIdOk ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetDogmaDynamicItemsTypeIdItemIdOk ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetDogmaDynamicItemsTypeIdItemIdOk *GetDogmaDynamicItemsTypeIdItemIdOk

func ( GetDogmaDynamicItemsTypeIdItemIdOkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetDogmaDynamicItemsTypeIdItemIdOkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetDogmaDynamicItemsTypeIdItemIdOkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetDogmaDynamicItemsTypeIdItemIdOkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetDogmaDynamicItemsTypeIdItemIdOkList *GetDogmaDynamicItemsTypeIdItemIdOkList
