// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetMarketsPrices200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetMarketsPrices200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetMarketsPrices200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetMarketsPrices200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetMarketsPrices200Ok *GetMarketsPrices200Ok

func ( GetMarketsPrices200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetMarketsPrices200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetMarketsPrices200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetMarketsPrices200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetMarketsPrices200OkList *GetMarketsPrices200OkList
