// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCorporationsCorporationIdOrders200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdOrders200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdOrders200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdOrders200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdOrders200Ok *GetCorporationsCorporationIdOrders200Ok

func ( GetCorporationsCorporationIdOrders200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdOrders200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdOrders200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdOrders200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdOrders200OkList *GetCorporationsCorporationIdOrders200OkList
