// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCorporationsCorporationIdStarbases200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdStarbases200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdStarbases200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdStarbases200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdStarbases200Ok *GetCorporationsCorporationIdStarbases200Ok

func ( GetCorporationsCorporationIdStarbases200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdStarbases200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdStarbases200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdStarbases200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdStarbases200OkList *GetCorporationsCorporationIdStarbases200OkList
