// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetFwLeaderboardsCharactersActiveTotalActiveTotal1 ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFwLeaderboardsCharactersActiveTotalActiveTotal1 ) UnmarshalJSON([]byte) error { return nil }
func ( GetFwLeaderboardsCharactersActiveTotalActiveTotal1 ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFwLeaderboardsCharactersActiveTotalActiveTotal1 ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFwLeaderboardsCharactersActiveTotalActiveTotal1 *GetFwLeaderboardsCharactersActiveTotalActiveTotal1

func ( GetFwLeaderboardsCharactersActiveTotalActiveTotal1List ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFwLeaderboardsCharactersActiveTotalActiveTotal1List ) UnmarshalJSON([]byte) error { return nil }
func ( GetFwLeaderboardsCharactersActiveTotalActiveTotal1List ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFwLeaderboardsCharactersActiveTotalActiveTotal1List ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFwLeaderboardsCharactersActiveTotalActiveTotal1List *GetFwLeaderboardsCharactersActiveTotalActiveTotal1List
