// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCharactersCharacterIdCalendarEventIdAttendeesNotFound ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdCalendarEventIdAttendeesNotFound ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdCalendarEventIdAttendeesNotFound ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdCalendarEventIdAttendeesNotFound ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdCalendarEventIdAttendeesNotFound *GetCharactersCharacterIdCalendarEventIdAttendeesNotFound

func ( GetCharactersCharacterIdCalendarEventIdAttendeesNotFoundList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdCalendarEventIdAttendeesNotFoundList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdCalendarEventIdAttendeesNotFoundList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdCalendarEventIdAttendeesNotFoundList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdCalendarEventIdAttendeesNotFoundList *GetCharactersCharacterIdCalendarEventIdAttendeesNotFoundList
