// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( PostFleetsFleetIdMembersInvitation ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostFleetsFleetIdMembersInvitation ) UnmarshalJSON([]byte) error { return nil }
func ( PostFleetsFleetIdMembersInvitation ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostFleetsFleetIdMembersInvitation ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostFleetsFleetIdMembersInvitation *PostFleetsFleetIdMembersInvitation

func ( PostFleetsFleetIdMembersInvitationList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostFleetsFleetIdMembersInvitationList ) UnmarshalJSON([]byte) error { return nil }
func ( PostFleetsFleetIdMembersInvitationList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostFleetsFleetIdMembersInvitationList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostFleetsFleetIdMembersInvitationList *PostFleetsFleetIdMembersInvitationList
