// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetUniverseSystemsSystemIdPosition ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseSystemsSystemIdPosition ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseSystemsSystemIdPosition ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseSystemsSystemIdPosition ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseSystemsSystemIdPosition *GetUniverseSystemsSystemIdPosition

func ( GetUniverseSystemsSystemIdPositionList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseSystemsSystemIdPositionList ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseSystemsSystemIdPositionList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseSystemsSystemIdPositionList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseSystemsSystemIdPositionList *GetUniverseSystemsSystemIdPositionList
