// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCorporationsCorporationIdWallets200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdWallets200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdWallets200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdWallets200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdWallets200Ok *GetCorporationsCorporationIdWallets200Ok

func ( GetCorporationsCorporationIdWallets200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdWallets200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdWallets200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdWallets200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdWallets200OkList *GetCorporationsCorporationIdWallets200OkList
