// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetWarsWarIdAlly ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetWarsWarIdAlly ) UnmarshalJSON([]byte) error { return nil }
func ( GetWarsWarIdAlly ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetWarsWarIdAlly ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetWarsWarIdAlly *GetWarsWarIdAlly

func ( GetWarsWarIdAllyList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetWarsWarIdAllyList ) UnmarshalJSON([]byte) error { return nil }
func ( GetWarsWarIdAllyList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetWarsWarIdAllyList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetWarsWarIdAllyList *GetWarsWarIdAllyList
