// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( PutFleetsFleetIdMembersMemberIdMovement ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PutFleetsFleetIdMembersMemberIdMovement ) UnmarshalJSON([]byte) error { return nil }
func ( PutFleetsFleetIdMembersMemberIdMovement ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PutFleetsFleetIdMembersMemberIdMovement ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PutFleetsFleetIdMembersMemberIdMovement *PutFleetsFleetIdMembersMemberIdMovement

func ( PutFleetsFleetIdMembersMemberIdMovementList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PutFleetsFleetIdMembersMemberIdMovementList ) UnmarshalJSON([]byte) error { return nil }
func ( PutFleetsFleetIdMembersMemberIdMovementList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PutFleetsFleetIdMembersMemberIdMovementList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PutFleetsFleetIdMembersMemberIdMovementList *PutFleetsFleetIdMembersMemberIdMovementList
