// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCorporationsCorporationIdContacts200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdContacts200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdContacts200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdContacts200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdContacts200Ok *GetCorporationsCorporationIdContacts200Ok

func ( GetCorporationsCorporationIdContacts200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdContacts200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdContacts200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdContacts200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdContacts200OkList *GetCorporationsCorporationIdContacts200OkList
