// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCorporationsCorporationIdContainersLogs200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdContainersLogs200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdContainersLogs200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdContainersLogs200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdContainersLogs200Ok *GetCorporationsCorporationIdContainersLogs200Ok

func ( GetCorporationsCorporationIdContainersLogs200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdContainersLogs200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdContainersLogs200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdContainersLogs200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdContainersLogs200OkList *GetCorporationsCorporationIdContainersLogs200OkList
