// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetWarsWarIdKillmails200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetWarsWarIdKillmails200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetWarsWarIdKillmails200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetWarsWarIdKillmails200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetWarsWarIdKillmails200Ok *GetWarsWarIdKillmails200Ok

func ( GetWarsWarIdKillmails200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetWarsWarIdKillmails200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetWarsWarIdKillmails200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetWarsWarIdKillmails200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetWarsWarIdKillmails200OkList *GetWarsWarIdKillmails200OkList
