// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCharactersCharacterIdOrdersHistory200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdOrdersHistory200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdOrdersHistory200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdOrdersHistory200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdOrdersHistory200Ok *GetCharactersCharacterIdOrdersHistory200Ok

func ( GetCharactersCharacterIdOrdersHistory200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdOrdersHistory200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdOrdersHistory200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdOrdersHistory200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdOrdersHistory200OkList *GetCharactersCharacterIdOrdersHistory200OkList
