// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetAlliancesAllianceIdIconsNotFound ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetAlliancesAllianceIdIconsNotFound ) UnmarshalJSON([]byte) error { return nil }
func ( GetAlliancesAllianceIdIconsNotFound ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetAlliancesAllianceIdIconsNotFound ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetAlliancesAllianceIdIconsNotFound *GetAlliancesAllianceIdIconsNotFound

func ( GetAlliancesAllianceIdIconsNotFoundList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetAlliancesAllianceIdIconsNotFoundList ) UnmarshalJSON([]byte) error { return nil }
func ( GetAlliancesAllianceIdIconsNotFoundList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetAlliancesAllianceIdIconsNotFoundList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetAlliancesAllianceIdIconsNotFoundList *GetAlliancesAllianceIdIconsNotFoundList
