// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( DeleteFleetsFleetIdMembersMemberIdNotFound ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* DeleteFleetsFleetIdMembersMemberIdNotFound ) UnmarshalJSON([]byte) error { return nil }
func ( DeleteFleetsFleetIdMembersMemberIdNotFound ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* DeleteFleetsFleetIdMembersMemberIdNotFound ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_DeleteFleetsFleetIdMembersMemberIdNotFound *DeleteFleetsFleetIdMembersMemberIdNotFound

func ( DeleteFleetsFleetIdMembersMemberIdNotFoundList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* DeleteFleetsFleetIdMembersMemberIdNotFoundList ) UnmarshalJSON([]byte) error { return nil }
func ( DeleteFleetsFleetIdMembersMemberIdNotFoundList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* DeleteFleetsFleetIdMembersMemberIdNotFoundList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_DeleteFleetsFleetIdMembersMemberIdNotFoundList *DeleteFleetsFleetIdMembersMemberIdNotFoundList
