// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetAlliancesAllianceIdContactsLabels200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetAlliancesAllianceIdContactsLabels200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetAlliancesAllianceIdContactsLabels200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetAlliancesAllianceIdContactsLabels200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetAlliancesAllianceIdContactsLabels200Ok *GetAlliancesAllianceIdContactsLabels200Ok

func ( GetAlliancesAllianceIdContactsLabels200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetAlliancesAllianceIdContactsLabels200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetAlliancesAllianceIdContactsLabels200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetAlliancesAllianceIdContactsLabels200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetAlliancesAllianceIdContactsLabels200OkList *GetAlliancesAllianceIdContactsLabels200OkList
