// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCharactersCharacterIdCorporationhistory200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdCorporationhistory200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdCorporationhistory200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdCorporationhistory200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdCorporationhistory200Ok *GetCharactersCharacterIdCorporationhistory200Ok

func ( GetCharactersCharacterIdCorporationhistory200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdCorporationhistory200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdCorporationhistory200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdCorporationhistory200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdCorporationhistory200OkList *GetCharactersCharacterIdCorporationhistory200OkList
