// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetDogmaEffectsEffectIdOk ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetDogmaEffectsEffectIdOk ) UnmarshalJSON([]byte) error { return nil }
func ( GetDogmaEffectsEffectIdOk ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetDogmaEffectsEffectIdOk ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetDogmaEffectsEffectIdOk *GetDogmaEffectsEffectIdOk

func ( GetDogmaEffectsEffectIdOkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetDogmaEffectsEffectIdOkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetDogmaEffectsEffectIdOkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetDogmaEffectsEffectIdOkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetDogmaEffectsEffectIdOkList *GetDogmaEffectsEffectIdOkList
