// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetFwLeaderboardsCorporationsActiveTotalActiveTotal ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFwLeaderboardsCorporationsActiveTotalActiveTotal ) UnmarshalJSON([]byte) error { return nil }
func ( GetFwLeaderboardsCorporationsActiveTotalActiveTotal ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFwLeaderboardsCorporationsActiveTotalActiveTotal ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFwLeaderboardsCorporationsActiveTotalActiveTotal *GetFwLeaderboardsCorporationsActiveTotalActiveTotal

func ( GetFwLeaderboardsCorporationsActiveTotalActiveTotalList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFwLeaderboardsCorporationsActiveTotalActiveTotalList ) UnmarshalJSON([]byte) error { return nil }
func ( GetFwLeaderboardsCorporationsActiveTotalActiveTotalList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFwLeaderboardsCorporationsActiveTotalActiveTotalList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFwLeaderboardsCorporationsActiveTotalActiveTotalList *GetFwLeaderboardsCorporationsActiveTotalActiveTotalList
