// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetContractsPublicBidsContractIdNotFound ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetContractsPublicBidsContractIdNotFound ) UnmarshalJSON([]byte) error { return nil }
func ( GetContractsPublicBidsContractIdNotFound ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetContractsPublicBidsContractIdNotFound ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetContractsPublicBidsContractIdNotFound *GetContractsPublicBidsContractIdNotFound

func ( GetContractsPublicBidsContractIdNotFoundList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetContractsPublicBidsContractIdNotFoundList ) UnmarshalJSON([]byte) error { return nil }
func ( GetContractsPublicBidsContractIdNotFoundList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetContractsPublicBidsContractIdNotFoundList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetContractsPublicBidsContractIdNotFoundList *GetContractsPublicBidsContractIdNotFoundList
