// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetStatusOk ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetStatusOk ) UnmarshalJSON([]byte) error { return nil }
func ( GetStatusOk ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetStatusOk ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetStatusOk *GetStatusOk

func ( GetStatusOkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetStatusOkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetStatusOkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetStatusOkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetStatusOkList *GetStatusOkList
