// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCharactersCharacterIdTitles200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdTitles200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdTitles200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdTitles200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdTitles200Ok *GetCharactersCharacterIdTitles200Ok

func ( GetCharactersCharacterIdTitles200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdTitles200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdTitles200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdTitles200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdTitles200OkList *GetCharactersCharacterIdTitles200OkList
