// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetUniverseGraphicsGraphicIdNotFound ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseGraphicsGraphicIdNotFound ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseGraphicsGraphicIdNotFound ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseGraphicsGraphicIdNotFound ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseGraphicsGraphicIdNotFound *GetUniverseGraphicsGraphicIdNotFound

func ( GetUniverseGraphicsGraphicIdNotFoundList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseGraphicsGraphicIdNotFoundList ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseGraphicsGraphicIdNotFoundList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseGraphicsGraphicIdNotFoundList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseGraphicsGraphicIdNotFoundList *GetUniverseGraphicsGraphicIdNotFoundList
