// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetDogmaDynamicItemsTypeIdItemIdDogmaEffect ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetDogmaDynamicItemsTypeIdItemIdDogmaEffect ) UnmarshalJSON([]byte) error { return nil }
func ( GetDogmaDynamicItemsTypeIdItemIdDogmaEffect ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetDogmaDynamicItemsTypeIdItemIdDogmaEffect ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetDogmaDynamicItemsTypeIdItemIdDogmaEffect *GetDogmaDynamicItemsTypeIdItemIdDogmaEffect

func ( GetDogmaDynamicItemsTypeIdItemIdDogmaEffectList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetDogmaDynamicItemsTypeIdItemIdDogmaEffectList ) UnmarshalJSON([]byte) error { return nil }
func ( GetDogmaDynamicItemsTypeIdItemIdDogmaEffectList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetDogmaDynamicItemsTypeIdItemIdDogmaEffectList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetDogmaDynamicItemsTypeIdItemIdDogmaEffectList *GetDogmaDynamicItemsTypeIdItemIdDogmaEffectList
