// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCharactersCharacterIdSkillqueue200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdSkillqueue200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdSkillqueue200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdSkillqueue200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdSkillqueue200Ok *GetCharactersCharacterIdSkillqueue200Ok

func ( GetCharactersCharacterIdSkillqueue200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdSkillqueue200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdSkillqueue200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdSkillqueue200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdSkillqueue200OkList *GetCharactersCharacterIdSkillqueue200OkList
