// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetFwLeaderboardsOk ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFwLeaderboardsOk ) UnmarshalJSON([]byte) error { return nil }
func ( GetFwLeaderboardsOk ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFwLeaderboardsOk ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFwLeaderboardsOk *GetFwLeaderboardsOk

func ( GetFwLeaderboardsOkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFwLeaderboardsOkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetFwLeaderboardsOkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFwLeaderboardsOkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFwLeaderboardsOkList *GetFwLeaderboardsOkList
