// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( PostCharactersAffiliation200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostCharactersAffiliation200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( PostCharactersAffiliation200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostCharactersAffiliation200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostCharactersAffiliation200Ok *PostCharactersAffiliation200Ok

func ( PostCharactersAffiliation200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostCharactersAffiliation200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( PostCharactersAffiliation200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostCharactersAffiliation200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostCharactersAffiliation200OkList *PostCharactersAffiliation200OkList
