// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetFwLeaderboardsYesterdayYesterday1 ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFwLeaderboardsYesterdayYesterday1 ) UnmarshalJSON([]byte) error { return nil }
func ( GetFwLeaderboardsYesterdayYesterday1 ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFwLeaderboardsYesterdayYesterday1 ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFwLeaderboardsYesterdayYesterday1 *GetFwLeaderboardsYesterdayYesterday1

func ( GetFwLeaderboardsYesterdayYesterday1List ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFwLeaderboardsYesterdayYesterday1List ) UnmarshalJSON([]byte) error { return nil }
func ( GetFwLeaderboardsYesterdayYesterday1List ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFwLeaderboardsYesterdayYesterday1List ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFwLeaderboardsYesterdayYesterday1List *GetFwLeaderboardsYesterdayYesterday1List
