// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetIndustrySystems200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetIndustrySystems200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetIndustrySystems200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetIndustrySystems200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetIndustrySystems200Ok *GetIndustrySystems200Ok

func ( GetIndustrySystems200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetIndustrySystems200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetIndustrySystems200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetIndustrySystems200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetIndustrySystems200OkList *GetIndustrySystems200OkList
