// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCharactersCharacterIdNotifications200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdNotifications200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdNotifications200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdNotifications200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdNotifications200Ok *GetCharactersCharacterIdNotifications200Ok

func ( GetCharactersCharacterIdNotifications200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdNotifications200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdNotifications200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdNotifications200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdNotifications200OkList *GetCharactersCharacterIdNotifications200OkList
