// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetFwSystems200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFwSystems200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetFwSystems200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFwSystems200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFwSystems200Ok *GetFwSystems200Ok

func ( GetFwSystems200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFwSystems200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetFwSystems200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFwSystems200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFwSystems200OkList *GetFwSystems200OkList
