// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetMarketsGroupsMarketGroupIdOk ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetMarketsGroupsMarketGroupIdOk ) UnmarshalJSON([]byte) error { return nil }
func ( GetMarketsGroupsMarketGroupIdOk ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetMarketsGroupsMarketGroupIdOk ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetMarketsGroupsMarketGroupIdOk *GetMarketsGroupsMarketGroupIdOk

func ( GetMarketsGroupsMarketGroupIdOkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetMarketsGroupsMarketGroupIdOkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetMarketsGroupsMarketGroupIdOkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetMarketsGroupsMarketGroupIdOkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetMarketsGroupsMarketGroupIdOkList *GetMarketsGroupsMarketGroupIdOkList
