// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCharactersCharacterIdFittingsItem ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdFittingsItem ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdFittingsItem ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdFittingsItem ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdFittingsItem *GetCharactersCharacterIdFittingsItem

func ( GetCharactersCharacterIdFittingsItemList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdFittingsItemList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdFittingsItemList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdFittingsItemList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdFittingsItemList *GetCharactersCharacterIdFittingsItemList
