// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetContractsPublicRegionIdNotFound ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetContractsPublicRegionIdNotFound ) UnmarshalJSON([]byte) error { return nil }
func ( GetContractsPublicRegionIdNotFound ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetContractsPublicRegionIdNotFound ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetContractsPublicRegionIdNotFound *GetContractsPublicRegionIdNotFound

func ( GetContractsPublicRegionIdNotFoundList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetContractsPublicRegionIdNotFoundList ) UnmarshalJSON([]byte) error { return nil }
func ( GetContractsPublicRegionIdNotFoundList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetContractsPublicRegionIdNotFoundList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetContractsPublicRegionIdNotFoundList *GetContractsPublicRegionIdNotFoundList
