// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCharactersCharacterIdClonesOk ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdClonesOk ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdClonesOk ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdClonesOk ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdClonesOk *GetCharactersCharacterIdClonesOk

func ( GetCharactersCharacterIdClonesOkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdClonesOkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdClonesOkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdClonesOkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdClonesOkList *GetCharactersCharacterIdClonesOkList
