// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCharactersCharacterIdPlanetsPlanetIdExtractorDetails ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdPlanetsPlanetIdExtractorDetails ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdPlanetsPlanetIdExtractorDetails ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdPlanetsPlanetIdExtractorDetails ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdPlanetsPlanetIdExtractorDetails *GetCharactersCharacterIdPlanetsPlanetIdExtractorDetails

func ( GetCharactersCharacterIdPlanetsPlanetIdExtractorDetailsList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdPlanetsPlanetIdExtractorDetailsList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdPlanetsPlanetIdExtractorDetailsList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdPlanetsPlanetIdExtractorDetailsList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdPlanetsPlanetIdExtractorDetailsList *GetCharactersCharacterIdPlanetsPlanetIdExtractorDetailsList
