// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( PostCorporationsCorporationIdAssetsNames200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostCorporationsCorporationIdAssetsNames200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( PostCorporationsCorporationIdAssetsNames200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostCorporationsCorporationIdAssetsNames200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostCorporationsCorporationIdAssetsNames200Ok *PostCorporationsCorporationIdAssetsNames200Ok

func ( PostCorporationsCorporationIdAssetsNames200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostCorporationsCorporationIdAssetsNames200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( PostCorporationsCorporationIdAssetsNames200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostCorporationsCorporationIdAssetsNames200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostCorporationsCorporationIdAssetsNames200OkList *PostCorporationsCorporationIdAssetsNames200OkList
