// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( DeleteFleetsFleetIdWingsWingIdNotFound ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* DeleteFleetsFleetIdWingsWingIdNotFound ) UnmarshalJSON([]byte) error { return nil }
func ( DeleteFleetsFleetIdWingsWingIdNotFound ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* DeleteFleetsFleetIdWingsWingIdNotFound ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_DeleteFleetsFleetIdWingsWingIdNotFound *DeleteFleetsFleetIdWingsWingIdNotFound

func ( DeleteFleetsFleetIdWingsWingIdNotFoundList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* DeleteFleetsFleetIdWingsWingIdNotFoundList ) UnmarshalJSON([]byte) error { return nil }
func ( DeleteFleetsFleetIdWingsWingIdNotFoundList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* DeleteFleetsFleetIdWingsWingIdNotFoundList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_DeleteFleetsFleetIdWingsWingIdNotFoundList *DeleteFleetsFleetIdWingsWingIdNotFoundList
