// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( PostCharactersCharacterIdMailLabelsLabel ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostCharactersCharacterIdMailLabelsLabel ) UnmarshalJSON([]byte) error { return nil }
func ( PostCharactersCharacterIdMailLabelsLabel ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostCharactersCharacterIdMailLabelsLabel ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostCharactersCharacterIdMailLabelsLabel *PostCharactersCharacterIdMailLabelsLabel

func ( PostCharactersCharacterIdMailLabelsLabelList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostCharactersCharacterIdMailLabelsLabelList ) UnmarshalJSON([]byte) error { return nil }
func ( PostCharactersCharacterIdMailLabelsLabelList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostCharactersCharacterIdMailLabelsLabelList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostCharactersCharacterIdMailLabelsLabelList *PostCharactersCharacterIdMailLabelsLabelList
