// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( PutCharactersCharacterIdCalendarEventIdResponse ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PutCharactersCharacterIdCalendarEventIdResponse ) UnmarshalJSON([]byte) error { return nil }
func ( PutCharactersCharacterIdCalendarEventIdResponse ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PutCharactersCharacterIdCalendarEventIdResponse ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PutCharactersCharacterIdCalendarEventIdResponse *PutCharactersCharacterIdCalendarEventIdResponse

func ( PutCharactersCharacterIdCalendarEventIdResponseList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PutCharactersCharacterIdCalendarEventIdResponseList ) UnmarshalJSON([]byte) error { return nil }
func ( PutCharactersCharacterIdCalendarEventIdResponseList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PutCharactersCharacterIdCalendarEventIdResponseList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PutCharactersCharacterIdCalendarEventIdResponseList *PutCharactersCharacterIdCalendarEventIdResponseList
