// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetUniverseGroupsGroupIdOk ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseGroupsGroupIdOk ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseGroupsGroupIdOk ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseGroupsGroupIdOk ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseGroupsGroupIdOk *GetUniverseGroupsGroupIdOk

func ( GetUniverseGroupsGroupIdOkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseGroupsGroupIdOkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseGroupsGroupIdOkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseGroupsGroupIdOkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseGroupsGroupIdOkList *GetUniverseGroupsGroupIdOkList
