// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCharactersCharacterIdBookmarks200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdBookmarks200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdBookmarks200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdBookmarks200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdBookmarks200Ok *GetCharactersCharacterIdBookmarks200Ok

func ( GetCharactersCharacterIdBookmarks200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdBookmarks200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdBookmarks200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdBookmarks200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdBookmarks200OkList *GetCharactersCharacterIdBookmarks200OkList
