// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCorporationsCorporationIdIndustryJobs200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdIndustryJobs200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdIndustryJobs200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdIndustryJobs200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdIndustryJobs200Ok *GetCorporationsCorporationIdIndustryJobs200Ok

func ( GetCorporationsCorporationIdIndustryJobs200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdIndustryJobs200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdIndustryJobs200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdIndustryJobs200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdIndustryJobs200OkList *GetCorporationsCorporationIdIndustryJobs200OkList
