// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCorporationsCorporationIdFwStatsVictoryPoints ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdFwStatsVictoryPoints ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdFwStatsVictoryPoints ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdFwStatsVictoryPoints ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdFwStatsVictoryPoints *GetCorporationsCorporationIdFwStatsVictoryPoints

func ( GetCorporationsCorporationIdFwStatsVictoryPointsList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdFwStatsVictoryPointsList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdFwStatsVictoryPointsList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdFwStatsVictoryPointsList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdFwStatsVictoryPointsList *GetCorporationsCorporationIdFwStatsVictoryPointsList
