// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetFwLeaderboardsCorporationsYesterdayYesterday ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFwLeaderboardsCorporationsYesterdayYesterday ) UnmarshalJSON([]byte) error { return nil }
func ( GetFwLeaderboardsCorporationsYesterdayYesterday ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFwLeaderboardsCorporationsYesterdayYesterday ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFwLeaderboardsCorporationsYesterdayYesterday *GetFwLeaderboardsCorporationsYesterdayYesterday

func ( GetFwLeaderboardsCorporationsYesterdayYesterdayList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFwLeaderboardsCorporationsYesterdayYesterdayList ) UnmarshalJSON([]byte) error { return nil }
func ( GetFwLeaderboardsCorporationsYesterdayYesterdayList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFwLeaderboardsCorporationsYesterdayYesterdayList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFwLeaderboardsCorporationsYesterdayYesterdayList *GetFwLeaderboardsCorporationsYesterdayYesterdayList
