// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCharactersCharacterIdFwStatsKills ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdFwStatsKills ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdFwStatsKills ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdFwStatsKills ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdFwStatsKills *GetCharactersCharacterIdFwStatsKills

func ( GetCharactersCharacterIdFwStatsKillsList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdFwStatsKillsList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdFwStatsKillsList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdFwStatsKillsList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdFwStatsKillsList *GetCharactersCharacterIdFwStatsKillsList
