// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetMarketsRegionIdHistoryNotFound ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetMarketsRegionIdHistoryNotFound ) UnmarshalJSON([]byte) error { return nil }
func ( GetMarketsRegionIdHistoryNotFound ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetMarketsRegionIdHistoryNotFound ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetMarketsRegionIdHistoryNotFound *GetMarketsRegionIdHistoryNotFound

func ( GetMarketsRegionIdHistoryNotFoundList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetMarketsRegionIdHistoryNotFoundList ) UnmarshalJSON([]byte) error { return nil }
func ( GetMarketsRegionIdHistoryNotFoundList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetMarketsRegionIdHistoryNotFoundList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetMarketsRegionIdHistoryNotFoundList *GetMarketsRegionIdHistoryNotFoundList
