// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetDogmaAttributesAttributeIdNotFound ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetDogmaAttributesAttributeIdNotFound ) UnmarshalJSON([]byte) error { return nil }
func ( GetDogmaAttributesAttributeIdNotFound ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetDogmaAttributesAttributeIdNotFound ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetDogmaAttributesAttributeIdNotFound *GetDogmaAttributesAttributeIdNotFound

func ( GetDogmaAttributesAttributeIdNotFoundList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetDogmaAttributesAttributeIdNotFoundList ) UnmarshalJSON([]byte) error { return nil }
func ( GetDogmaAttributesAttributeIdNotFoundList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetDogmaAttributesAttributeIdNotFoundList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetDogmaAttributesAttributeIdNotFoundList *GetDogmaAttributesAttributeIdNotFoundList
