// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( PutFleetsFleetIdNotFound ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PutFleetsFleetIdNotFound ) UnmarshalJSON([]byte) error { return nil }
func ( PutFleetsFleetIdNotFound ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PutFleetsFleetIdNotFound ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PutFleetsFleetIdNotFound *PutFleetsFleetIdNotFound

func ( PutFleetsFleetIdNotFoundList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PutFleetsFleetIdNotFoundList ) UnmarshalJSON([]byte) error { return nil }
func ( PutFleetsFleetIdNotFoundList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PutFleetsFleetIdNotFoundList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PutFleetsFleetIdNotFoundList *PutFleetsFleetIdNotFoundList
