// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetKillmailsKillmailIdKillmailHashPosition ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetKillmailsKillmailIdKillmailHashPosition ) UnmarshalJSON([]byte) error { return nil }
func ( GetKillmailsKillmailIdKillmailHashPosition ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetKillmailsKillmailIdKillmailHashPosition ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetKillmailsKillmailIdKillmailHashPosition *GetKillmailsKillmailIdKillmailHashPosition

func ( GetKillmailsKillmailIdKillmailHashPositionList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetKillmailsKillmailIdKillmailHashPositionList ) UnmarshalJSON([]byte) error { return nil }
func ( GetKillmailsKillmailIdKillmailHashPositionList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetKillmailsKillmailIdKillmailHashPositionList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetKillmailsKillmailIdKillmailHashPositionList *GetKillmailsKillmailIdKillmailHashPositionList
