// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCharactersCharacterIdMailLists200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdMailLists200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdMailLists200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdMailLists200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdMailLists200Ok *GetCharactersCharacterIdMailLists200Ok

func ( GetCharactersCharacterIdMailLists200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdMailLists200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdMailLists200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdMailLists200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdMailLists200OkList *GetCharactersCharacterIdMailLists200OkList
