// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( PostCharactersCharacterIdAssetsNames200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostCharactersCharacterIdAssetsNames200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( PostCharactersCharacterIdAssetsNames200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostCharactersCharacterIdAssetsNames200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostCharactersCharacterIdAssetsNames200Ok *PostCharactersCharacterIdAssetsNames200Ok

func ( PostCharactersCharacterIdAssetsNames200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostCharactersCharacterIdAssetsNames200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( PostCharactersCharacterIdAssetsNames200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostCharactersCharacterIdAssetsNames200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostCharactersCharacterIdAssetsNames200OkList *PostCharactersCharacterIdAssetsNames200OkList
