// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetContractsPublicItemsContractIdForbidden ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetContractsPublicItemsContractIdForbidden ) UnmarshalJSON([]byte) error { return nil }
func ( GetContractsPublicItemsContractIdForbidden ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetContractsPublicItemsContractIdForbidden ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetContractsPublicItemsContractIdForbidden *GetContractsPublicItemsContractIdForbidden

func ( GetContractsPublicItemsContractIdForbiddenList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetContractsPublicItemsContractIdForbiddenList ) UnmarshalJSON([]byte) error { return nil }
func ( GetContractsPublicItemsContractIdForbiddenList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetContractsPublicItemsContractIdForbiddenList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetContractsPublicItemsContractIdForbiddenList *GetContractsPublicItemsContractIdForbiddenList
