// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCorporationsCorporationIdWalletsDivisionTransactions200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdWalletsDivisionTransactions200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdWalletsDivisionTransactions200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdWalletsDivisionTransactions200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdWalletsDivisionTransactions200Ok *GetCorporationsCorporationIdWalletsDivisionTransactions200Ok

func ( GetCorporationsCorporationIdWalletsDivisionTransactions200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdWalletsDivisionTransactions200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdWalletsDivisionTransactions200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdWalletsDivisionTransactions200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdWalletsDivisionTransactions200OkList *GetCorporationsCorporationIdWalletsDivisionTransactions200OkList
