// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetContractsPublicRegionId200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetContractsPublicRegionId200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetContractsPublicRegionId200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetContractsPublicRegionId200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetContractsPublicRegionId200Ok *GetContractsPublicRegionId200Ok

func ( GetContractsPublicRegionId200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetContractsPublicRegionId200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetContractsPublicRegionId200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetContractsPublicRegionId200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetContractsPublicRegionId200OkList *GetContractsPublicRegionId200OkList
