// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetFwLeaderboardsCharactersActiveTotalActiveTotal ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFwLeaderboardsCharactersActiveTotalActiveTotal ) UnmarshalJSON([]byte) error { return nil }
func ( GetFwLeaderboardsCharactersActiveTotalActiveTotal ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFwLeaderboardsCharactersActiveTotalActiveTotal ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFwLeaderboardsCharactersActiveTotalActiveTotal *GetFwLeaderboardsCharactersActiveTotalActiveTotal

func ( GetFwLeaderboardsCharactersActiveTotalActiveTotalList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFwLeaderboardsCharactersActiveTotalActiveTotalList ) UnmarshalJSON([]byte) error { return nil }
func ( GetFwLeaderboardsCharactersActiveTotalActiveTotalList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFwLeaderboardsCharactersActiveTotalActiveTotalList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFwLeaderboardsCharactersActiveTotalActiveTotalList *GetFwLeaderboardsCharactersActiveTotalActiveTotalList
