// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetFwWars200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFwWars200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetFwWars200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFwWars200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFwWars200Ok *GetFwWars200Ok

func ( GetFwWars200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFwWars200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetFwWars200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFwWars200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFwWars200OkList *GetFwWars200OkList
