// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCorporationsCorporationIdKillmailsRecent200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdKillmailsRecent200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdKillmailsRecent200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdKillmailsRecent200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdKillmailsRecent200Ok *GetCorporationsCorporationIdKillmailsRecent200Ok

func ( GetCorporationsCorporationIdKillmailsRecent200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdKillmailsRecent200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdKillmailsRecent200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdKillmailsRecent200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdKillmailsRecent200OkList *GetCorporationsCorporationIdKillmailsRecent200OkList
