// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetContractsPublicBidsContractIdForbidden ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetContractsPublicBidsContractIdForbidden ) UnmarshalJSON([]byte) error { return nil }
func ( GetContractsPublicBidsContractIdForbidden ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetContractsPublicBidsContractIdForbidden ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetContractsPublicBidsContractIdForbidden *GetContractsPublicBidsContractIdForbidden

func ( GetContractsPublicBidsContractIdForbiddenList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetContractsPublicBidsContractIdForbiddenList ) UnmarshalJSON([]byte) error { return nil }
func ( GetContractsPublicBidsContractIdForbiddenList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetContractsPublicBidsContractIdForbiddenList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetContractsPublicBidsContractIdForbiddenList *GetContractsPublicBidsContractIdForbiddenList
