// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetFwStats200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFwStats200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetFwStats200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFwStats200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFwStats200Ok *GetFwStats200Ok

func ( GetFwStats200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFwStats200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetFwStats200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFwStats200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFwStats200OkList *GetFwStats200OkList
