// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetContractsPublicItemsContractId200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetContractsPublicItemsContractId200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetContractsPublicItemsContractId200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetContractsPublicItemsContractId200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetContractsPublicItemsContractId200Ok *GetContractsPublicItemsContractId200Ok

func ( GetContractsPublicItemsContractId200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetContractsPublicItemsContractId200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetContractsPublicItemsContractId200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetContractsPublicItemsContractId200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetContractsPublicItemsContractId200OkList *GetContractsPublicItemsContractId200OkList
