// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetUniverseRegionsRegionIdOk ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseRegionsRegionIdOk ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseRegionsRegionIdOk ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseRegionsRegionIdOk ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseRegionsRegionIdOk *GetUniverseRegionsRegionIdOk

func ( GetUniverseRegionsRegionIdOkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseRegionsRegionIdOkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseRegionsRegionIdOkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseRegionsRegionIdOkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseRegionsRegionIdOkList *GetUniverseRegionsRegionIdOkList
