// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCharactersCharacterIdContractsContractIdItems200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdContractsContractIdItems200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdContractsContractIdItems200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdContractsContractIdItems200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdContractsContractIdItems200Ok *GetCharactersCharacterIdContractsContractIdItems200Ok

func ( GetCharactersCharacterIdContractsContractIdItems200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdContractsContractIdItems200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdContractsContractIdItems200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdContractsContractIdItems200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdContractsContractIdItems200OkList *GetCharactersCharacterIdContractsContractIdItems200OkList
