// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCorporationsCorporationIdStructuresService ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdStructuresService ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdStructuresService ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdStructuresService ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdStructuresService *GetCorporationsCorporationIdStructuresService

func ( GetCorporationsCorporationIdStructuresServiceList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdStructuresServiceList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdStructuresServiceList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdStructuresServiceList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdStructuresServiceList *GetCorporationsCorporationIdStructuresServiceList
