// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCorporationsCorporationIdBookmarksItem ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdBookmarksItem ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdBookmarksItem ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdBookmarksItem ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdBookmarksItem *GetCorporationsCorporationIdBookmarksItem

func ( GetCorporationsCorporationIdBookmarksItemList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdBookmarksItemList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdBookmarksItemList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdBookmarksItemList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdBookmarksItemList *GetCorporationsCorporationIdBookmarksItemList
