// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCharactersCharacterIdMailLabelsOk ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdMailLabelsOk ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdMailLabelsOk ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdMailLabelsOk ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdMailLabelsOk *GetCharactersCharacterIdMailLabelsOk

func ( GetCharactersCharacterIdMailLabelsOkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdMailLabelsOkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdMailLabelsOkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdMailLabelsOkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdMailLabelsOkList *GetCharactersCharacterIdMailLabelsOkList
