// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetWarsWarIdOk ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetWarsWarIdOk ) UnmarshalJSON([]byte) error { return nil }
func ( GetWarsWarIdOk ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetWarsWarIdOk ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetWarsWarIdOk *GetWarsWarIdOk

func ( GetWarsWarIdOkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetWarsWarIdOkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetWarsWarIdOkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetWarsWarIdOkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetWarsWarIdOkList *GetWarsWarIdOkList
