// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( PostUniverseIdsSystem ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostUniverseIdsSystem ) UnmarshalJSON([]byte) error { return nil }
func ( PostUniverseIdsSystem ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostUniverseIdsSystem ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostUniverseIdsSystem *PostUniverseIdsSystem

func ( PostUniverseIdsSystemList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostUniverseIdsSystemList ) UnmarshalJSON([]byte) error { return nil }
func ( PostUniverseIdsSystemList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostUniverseIdsSystemList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostUniverseIdsSystemList *PostUniverseIdsSystemList
