// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( PostCharactersCharacterIdAssetsLocationsPosition ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostCharactersCharacterIdAssetsLocationsPosition ) UnmarshalJSON([]byte) error { return nil }
func ( PostCharactersCharacterIdAssetsLocationsPosition ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostCharactersCharacterIdAssetsLocationsPosition ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostCharactersCharacterIdAssetsLocationsPosition *PostCharactersCharacterIdAssetsLocationsPosition

func ( PostCharactersCharacterIdAssetsLocationsPositionList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostCharactersCharacterIdAssetsLocationsPositionList ) UnmarshalJSON([]byte) error { return nil }
func ( PostCharactersCharacterIdAssetsLocationsPositionList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostCharactersCharacterIdAssetsLocationsPositionList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostCharactersCharacterIdAssetsLocationsPositionList *PostCharactersCharacterIdAssetsLocationsPositionList
