// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetWarsWarIdDefender ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetWarsWarIdDefender ) UnmarshalJSON([]byte) error { return nil }
func ( GetWarsWarIdDefender ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetWarsWarIdDefender ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetWarsWarIdDefender *GetWarsWarIdDefender

func ( GetWarsWarIdDefenderList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetWarsWarIdDefenderList ) UnmarshalJSON([]byte) error { return nil }
func ( GetWarsWarIdDefenderList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetWarsWarIdDefenderList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetWarsWarIdDefenderList *GetWarsWarIdDefenderList
