// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCorporationsCorporationIdStarbasesStarbaseIdFuel ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdStarbasesStarbaseIdFuel ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdStarbasesStarbaseIdFuel ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdStarbasesStarbaseIdFuel ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdStarbasesStarbaseIdFuel *GetCorporationsCorporationIdStarbasesStarbaseIdFuel

func ( GetCorporationsCorporationIdStarbasesStarbaseIdFuelList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdStarbasesStarbaseIdFuelList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdStarbasesStarbaseIdFuelList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdStarbasesStarbaseIdFuelList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdStarbasesStarbaseIdFuelList *GetCorporationsCorporationIdStarbasesStarbaseIdFuelList
