// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( PostFleetsFleetIdWingsNotFound ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostFleetsFleetIdWingsNotFound ) UnmarshalJSON([]byte) error { return nil }
func ( PostFleetsFleetIdWingsNotFound ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostFleetsFleetIdWingsNotFound ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostFleetsFleetIdWingsNotFound *PostFleetsFleetIdWingsNotFound

func ( PostFleetsFleetIdWingsNotFoundList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostFleetsFleetIdWingsNotFoundList ) UnmarshalJSON([]byte) error { return nil }
func ( PostFleetsFleetIdWingsNotFoundList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostFleetsFleetIdWingsNotFoundList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostFleetsFleetIdWingsNotFoundList *PostFleetsFleetIdWingsNotFoundList
