// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetUniversePlanetsPlanetIdOk ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniversePlanetsPlanetIdOk ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniversePlanetsPlanetIdOk ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniversePlanetsPlanetIdOk ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniversePlanetsPlanetIdOk *GetUniversePlanetsPlanetIdOk

func ( GetUniversePlanetsPlanetIdOkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniversePlanetsPlanetIdOkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniversePlanetsPlanetIdOkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniversePlanetsPlanetIdOkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniversePlanetsPlanetIdOkList *GetUniversePlanetsPlanetIdOkList
