// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetUniverseTypesTypeIdDogmaEffect ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseTypesTypeIdDogmaEffect ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseTypesTypeIdDogmaEffect ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseTypesTypeIdDogmaEffect ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseTypesTypeIdDogmaEffect *GetUniverseTypesTypeIdDogmaEffect

func ( GetUniverseTypesTypeIdDogmaEffectList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseTypesTypeIdDogmaEffectList ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseTypesTypeIdDogmaEffectList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseTypesTypeIdDogmaEffectList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseTypesTypeIdDogmaEffectList *GetUniverseTypesTypeIdDogmaEffectList
