// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetUniverseStructuresStructureIdNotFound ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseStructuresStructureIdNotFound ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseStructuresStructureIdNotFound ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseStructuresStructureIdNotFound ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseStructuresStructureIdNotFound *GetUniverseStructuresStructureIdNotFound

func ( GetUniverseStructuresStructureIdNotFoundList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseStructuresStructureIdNotFoundList ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseStructuresStructureIdNotFoundList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseStructuresStructureIdNotFoundList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseStructuresStructureIdNotFoundList *GetUniverseStructuresStructureIdNotFoundList
