// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetUniverseStructuresStructureIdPosition ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseStructuresStructureIdPosition ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseStructuresStructureIdPosition ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseStructuresStructureIdPosition ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseStructuresStructureIdPosition *GetUniverseStructuresStructureIdPosition

func ( GetUniverseStructuresStructureIdPositionList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseStructuresStructureIdPositionList ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseStructuresStructureIdPositionList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseStructuresStructureIdPositionList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseStructuresStructureIdPositionList *GetUniverseStructuresStructureIdPositionList
