// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCorporationsCorporationIdIconsNotFound ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdIconsNotFound ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdIconsNotFound ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdIconsNotFound ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdIconsNotFound *GetCorporationsCorporationIdIconsNotFound

func ( GetCorporationsCorporationIdIconsNotFoundList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdIconsNotFoundList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdIconsNotFoundList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdIconsNotFoundList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdIconsNotFoundList *GetCorporationsCorporationIdIconsNotFoundList
