// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( PostFleetsFleetIdWingsCreated ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostFleetsFleetIdWingsCreated ) UnmarshalJSON([]byte) error { return nil }
func ( PostFleetsFleetIdWingsCreated ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostFleetsFleetIdWingsCreated ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostFleetsFleetIdWingsCreated *PostFleetsFleetIdWingsCreated

func ( PostFleetsFleetIdWingsCreatedList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostFleetsFleetIdWingsCreatedList ) UnmarshalJSON([]byte) error { return nil }
func ( PostFleetsFleetIdWingsCreatedList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostFleetsFleetIdWingsCreatedList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostFleetsFleetIdWingsCreatedList *PostFleetsFleetIdWingsCreatedList
