// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCharactersCharacterIdSkillsOk ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdSkillsOk ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdSkillsOk ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdSkillsOk ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdSkillsOk *GetCharactersCharacterIdSkillsOk

func ( GetCharactersCharacterIdSkillsOkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdSkillsOkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdSkillsOkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdSkillsOkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdSkillsOkList *GetCharactersCharacterIdSkillsOkList
