// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( DeleteFleetsFleetIdSquadsSquadIdNotFound ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* DeleteFleetsFleetIdSquadsSquadIdNotFound ) UnmarshalJSON([]byte) error { return nil }
func ( DeleteFleetsFleetIdSquadsSquadIdNotFound ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* DeleteFleetsFleetIdSquadsSquadIdNotFound ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_DeleteFleetsFleetIdSquadsSquadIdNotFound *DeleteFleetsFleetIdSquadsSquadIdNotFound

func ( DeleteFleetsFleetIdSquadsSquadIdNotFoundList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* DeleteFleetsFleetIdSquadsSquadIdNotFoundList ) UnmarshalJSON([]byte) error { return nil }
func ( DeleteFleetsFleetIdSquadsSquadIdNotFoundList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* DeleteFleetsFleetIdSquadsSquadIdNotFoundList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_DeleteFleetsFleetIdSquadsSquadIdNotFoundList *DeleteFleetsFleetIdSquadsSquadIdNotFoundList
