// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( PutFleetsFleetIdWingsWingIdNaming ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PutFleetsFleetIdWingsWingIdNaming ) UnmarshalJSON([]byte) error { return nil }
func ( PutFleetsFleetIdWingsWingIdNaming ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PutFleetsFleetIdWingsWingIdNaming ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PutFleetsFleetIdWingsWingIdNaming *PutFleetsFleetIdWingsWingIdNaming

func ( PutFleetsFleetIdWingsWingIdNamingList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PutFleetsFleetIdWingsWingIdNamingList ) UnmarshalJSON([]byte) error { return nil }
func ( PutFleetsFleetIdWingsWingIdNamingList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PutFleetsFleetIdWingsWingIdNamingList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PutFleetsFleetIdWingsWingIdNamingList *PutFleetsFleetIdWingsWingIdNamingList
