// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GatewayTimeout ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GatewayTimeout ) UnmarshalJSON([]byte) error { return nil }
func ( GatewayTimeout ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GatewayTimeout ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GatewayTimeout *GatewayTimeout

func ( GatewayTimeoutList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GatewayTimeoutList ) UnmarshalJSON([]byte) error { return nil }
func ( GatewayTimeoutList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GatewayTimeoutList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GatewayTimeoutList *GatewayTimeoutList
