// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetUniverseStationsStationIdNotFound ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseStationsStationIdNotFound ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseStationsStationIdNotFound ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseStationsStationIdNotFound ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseStationsStationIdNotFound *GetUniverseStationsStationIdNotFound

func ( GetUniverseStationsStationIdNotFoundList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseStationsStationIdNotFoundList ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseStationsStationIdNotFoundList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseStationsStationIdNotFoundList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseStationsStationIdNotFoundList *GetUniverseStationsStationIdNotFoundList
