// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetUniverseGraphicsGraphicIdOk ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseGraphicsGraphicIdOk ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseGraphicsGraphicIdOk ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseGraphicsGraphicIdOk ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseGraphicsGraphicIdOk *GetUniverseGraphicsGraphicIdOk

func ( GetUniverseGraphicsGraphicIdOkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseGraphicsGraphicIdOkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseGraphicsGraphicIdOkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseGraphicsGraphicIdOkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseGraphicsGraphicIdOkList *GetUniverseGraphicsGraphicIdOkList
