// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetLoyaltyStoresCorporationIdOffersRequiredItem ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetLoyaltyStoresCorporationIdOffersRequiredItem ) UnmarshalJSON([]byte) error { return nil }
func ( GetLoyaltyStoresCorporationIdOffersRequiredItem ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetLoyaltyStoresCorporationIdOffersRequiredItem ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetLoyaltyStoresCorporationIdOffersRequiredItem *GetLoyaltyStoresCorporationIdOffersRequiredItem

func ( GetLoyaltyStoresCorporationIdOffersRequiredItemList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetLoyaltyStoresCorporationIdOffersRequiredItemList ) UnmarshalJSON([]byte) error { return nil }
func ( GetLoyaltyStoresCorporationIdOffersRequiredItemList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetLoyaltyStoresCorporationIdOffersRequiredItemList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetLoyaltyStoresCorporationIdOffersRequiredItemList *GetLoyaltyStoresCorporationIdOffersRequiredItemList
