// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetFleetsFleetIdOk ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFleetsFleetIdOk ) UnmarshalJSON([]byte) error { return nil }
func ( GetFleetsFleetIdOk ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFleetsFleetIdOk ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFleetsFleetIdOk *GetFleetsFleetIdOk

func ( GetFleetsFleetIdOkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFleetsFleetIdOkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetFleetsFleetIdOkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFleetsFleetIdOkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFleetsFleetIdOkList *GetFleetsFleetIdOkList
