// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCharactersCharacterIdCalendar200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdCalendar200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdCalendar200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdCalendar200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdCalendar200Ok *GetCharactersCharacterIdCalendar200Ok

func ( GetCharactersCharacterIdCalendar200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdCalendar200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdCalendar200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdCalendar200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdCalendar200OkList *GetCharactersCharacterIdCalendar200OkList
