// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCharactersCharacterIdOpportunities200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdOpportunities200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdOpportunities200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdOpportunities200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdOpportunities200Ok *GetCharactersCharacterIdOpportunities200Ok

func ( GetCharactersCharacterIdOpportunities200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdOpportunities200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdOpportunities200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdOpportunities200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdOpportunities200OkList *GetCharactersCharacterIdOpportunities200OkList
