// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetOpportunitiesGroupsGroupIdOk ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetOpportunitiesGroupsGroupIdOk ) UnmarshalJSON([]byte) error { return nil }
func ( GetOpportunitiesGroupsGroupIdOk ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetOpportunitiesGroupsGroupIdOk ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetOpportunitiesGroupsGroupIdOk *GetOpportunitiesGroupsGroupIdOk

func ( GetOpportunitiesGroupsGroupIdOkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetOpportunitiesGroupsGroupIdOkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetOpportunitiesGroupsGroupIdOkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetOpportunitiesGroupsGroupIdOkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetOpportunitiesGroupsGroupIdOkList *GetOpportunitiesGroupsGroupIdOkList
