// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( PostUniverseIdsStation ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostUniverseIdsStation ) UnmarshalJSON([]byte) error { return nil }
func ( PostUniverseIdsStation ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostUniverseIdsStation ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostUniverseIdsStation *PostUniverseIdsStation

func ( PostUniverseIdsStationList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostUniverseIdsStationList ) UnmarshalJSON([]byte) error { return nil }
func ( PostUniverseIdsStationList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostUniverseIdsStationList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostUniverseIdsStationList *PostUniverseIdsStationList
