// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCorporationsCorporationIdDivisionsOk ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdDivisionsOk ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdDivisionsOk ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdDivisionsOk ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdDivisionsOk *GetCorporationsCorporationIdDivisionsOk

func ( GetCorporationsCorporationIdDivisionsOkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdDivisionsOkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdDivisionsOkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdDivisionsOkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdDivisionsOkList *GetCorporationsCorporationIdDivisionsOkList
