// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetFwLeaderboardsYesterdayYesterday ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFwLeaderboardsYesterdayYesterday ) UnmarshalJSON([]byte) error { return nil }
func ( GetFwLeaderboardsYesterdayYesterday ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFwLeaderboardsYesterdayYesterday ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFwLeaderboardsYesterdayYesterday *GetFwLeaderboardsYesterdayYesterday

func ( GetFwLeaderboardsYesterdayYesterdayList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFwLeaderboardsYesterdayYesterdayList ) UnmarshalJSON([]byte) error { return nil }
func ( GetFwLeaderboardsYesterdayYesterdayList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFwLeaderboardsYesterdayYesterdayList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFwLeaderboardsYesterdayYesterdayList *GetFwLeaderboardsYesterdayYesterdayList
