// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetUniverseFactions200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseFactions200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseFactions200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseFactions200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseFactions200Ok *GetUniverseFactions200Ok

func ( GetUniverseFactions200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseFactions200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseFactions200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseFactions200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseFactions200OkList *GetUniverseFactions200OkList
