// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCharactersCharacterIdPlanets200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdPlanets200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdPlanets200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdPlanets200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdPlanets200Ok *GetCharactersCharacterIdPlanets200Ok

func ( GetCharactersCharacterIdPlanets200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdPlanets200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdPlanets200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdPlanets200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdPlanets200OkList *GetCharactersCharacterIdPlanets200OkList
