// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetDogmaEffectsEffectIdNotFound ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetDogmaEffectsEffectIdNotFound ) UnmarshalJSON([]byte) error { return nil }
func ( GetDogmaEffectsEffectIdNotFound ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetDogmaEffectsEffectIdNotFound ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetDogmaEffectsEffectIdNotFound *GetDogmaEffectsEffectIdNotFound

func ( GetDogmaEffectsEffectIdNotFoundList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetDogmaEffectsEffectIdNotFoundList ) UnmarshalJSON([]byte) error { return nil }
func ( GetDogmaEffectsEffectIdNotFoundList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetDogmaEffectsEffectIdNotFoundList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetDogmaEffectsEffectIdNotFoundList *GetDogmaEffectsEffectIdNotFoundList
