// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCharactersCharacterIdCalendarEventIdOk ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdCalendarEventIdOk ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdCalendarEventIdOk ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdCalendarEventIdOk ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdCalendarEventIdOk *GetCharactersCharacterIdCalendarEventIdOk

func ( GetCharactersCharacterIdCalendarEventIdOkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdCalendarEventIdOkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdCalendarEventIdOkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdCalendarEventIdOkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdCalendarEventIdOkList *GetCharactersCharacterIdCalendarEventIdOkList
