// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetFleetsFleetIdNotFound ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFleetsFleetIdNotFound ) UnmarshalJSON([]byte) error { return nil }
func ( GetFleetsFleetIdNotFound ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFleetsFleetIdNotFound ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFleetsFleetIdNotFound *GetFleetsFleetIdNotFound

func ( GetFleetsFleetIdNotFoundList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFleetsFleetIdNotFoundList ) UnmarshalJSON([]byte) error { return nil }
func ( GetFleetsFleetIdNotFoundList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFleetsFleetIdNotFoundList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFleetsFleetIdNotFoundList *GetFleetsFleetIdNotFoundList
