// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCorporationsCorporationIdIconsOk ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdIconsOk ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdIconsOk ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdIconsOk ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdIconsOk *GetCorporationsCorporationIdIconsOk

func ( GetCorporationsCorporationIdIconsOkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdIconsOkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdIconsOkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdIconsOkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdIconsOkList *GetCorporationsCorporationIdIconsOkList
