// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( ErrorLimited ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* ErrorLimited ) UnmarshalJSON([]byte) error { return nil }
func ( ErrorLimited ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* ErrorLimited ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ErrorLimited *ErrorLimited

func ( ErrorLimitedList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* ErrorLimitedList ) UnmarshalJSON([]byte) error { return nil }
func ( ErrorLimitedList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* ErrorLimitedList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ErrorLimitedList *ErrorLimitedList
