// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetIndustrySystemsCostIndice ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetIndustrySystemsCostIndice ) UnmarshalJSON([]byte) error { return nil }
func ( GetIndustrySystemsCostIndice ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetIndustrySystemsCostIndice ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetIndustrySystemsCostIndice *GetIndustrySystemsCostIndice

func ( GetIndustrySystemsCostIndiceList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetIndustrySystemsCostIndiceList ) UnmarshalJSON([]byte) error { return nil }
func ( GetIndustrySystemsCostIndiceList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetIndustrySystemsCostIndiceList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetIndustrySystemsCostIndiceList *GetIndustrySystemsCostIndiceList
