// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetUniverseSystemKills200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseSystemKills200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseSystemKills200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseSystemKills200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseSystemKills200Ok *GetUniverseSystemKills200Ok

func ( GetUniverseSystemKills200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseSystemKills200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseSystemKills200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseSystemKills200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseSystemKills200OkList *GetUniverseSystemKills200OkList
