// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCharactersCharacterIdOrders200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdOrders200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdOrders200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdOrders200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdOrders200Ok *GetCharactersCharacterIdOrders200Ok

func ( GetCharactersCharacterIdOrders200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdOrders200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdOrders200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdOrders200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdOrders200OkList *GetCharactersCharacterIdOrders200OkList
