// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetFwLeaderboardsCharactersLastWeekLastWeek ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFwLeaderboardsCharactersLastWeekLastWeek ) UnmarshalJSON([]byte) error { return nil }
func ( GetFwLeaderboardsCharactersLastWeekLastWeek ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFwLeaderboardsCharactersLastWeekLastWeek ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFwLeaderboardsCharactersLastWeekLastWeek *GetFwLeaderboardsCharactersLastWeekLastWeek

func ( GetFwLeaderboardsCharactersLastWeekLastWeekList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetFwLeaderboardsCharactersLastWeekLastWeekList ) UnmarshalJSON([]byte) error { return nil }
func ( GetFwLeaderboardsCharactersLastWeekLastWeekList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetFwLeaderboardsCharactersLastWeekLastWeekList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetFwLeaderboardsCharactersLastWeekLastWeekList *GetFwLeaderboardsCharactersLastWeekLastWeekList
