// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCharactersCharacterIdFleetOk ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdFleetOk ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdFleetOk ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdFleetOk ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdFleetOk *GetCharactersCharacterIdFleetOk

func ( GetCharactersCharacterIdFleetOkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdFleetOkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdFleetOkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdFleetOkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdFleetOkList *GetCharactersCharacterIdFleetOkList
