// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetUniverseStargatesStargateIdOk ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseStargatesStargateIdOk ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseStargatesStargateIdOk ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseStargatesStargateIdOk ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseStargatesStargateIdOk *GetUniverseStargatesStargateIdOk

func ( GetUniverseStargatesStargateIdOkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseStargatesStargateIdOkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseStargatesStargateIdOkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseStargatesStargateIdOkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseStargatesStargateIdOkList *GetUniverseStargatesStargateIdOkList
