// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetUniverseAsteroidBeltsAsteroidBeltIdPosition ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseAsteroidBeltsAsteroidBeltIdPosition ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseAsteroidBeltsAsteroidBeltIdPosition ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseAsteroidBeltsAsteroidBeltIdPosition ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseAsteroidBeltsAsteroidBeltIdPosition *GetUniverseAsteroidBeltsAsteroidBeltIdPosition

func ( GetUniverseAsteroidBeltsAsteroidBeltIdPositionList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseAsteroidBeltsAsteroidBeltIdPositionList ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseAsteroidBeltsAsteroidBeltIdPositionList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseAsteroidBeltsAsteroidBeltIdPositionList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseAsteroidBeltsAsteroidBeltIdPositionList *GetUniverseAsteroidBeltsAsteroidBeltIdPositionList
