// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCharactersCharacterIdWalletJournal200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdWalletJournal200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdWalletJournal200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdWalletJournal200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdWalletJournal200Ok *GetCharactersCharacterIdWalletJournal200Ok

func ( GetCharactersCharacterIdWalletJournal200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdWalletJournal200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdWalletJournal200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdWalletJournal200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdWalletJournal200OkList *GetCharactersCharacterIdWalletJournal200OkList
