// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCharactersCharacterIdFleetNotFound ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdFleetNotFound ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdFleetNotFound ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdFleetNotFound ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdFleetNotFound *GetCharactersCharacterIdFleetNotFound

func ( GetCharactersCharacterIdFleetNotFoundList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdFleetNotFoundList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdFleetNotFoundList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdFleetNotFoundList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdFleetNotFoundList *GetCharactersCharacterIdFleetNotFoundList
