// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCharactersCharacterIdMailMailIdRecipient ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdMailMailIdRecipient ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdMailMailIdRecipient ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdMailMailIdRecipient ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdMailMailIdRecipient *GetCharactersCharacterIdMailMailIdRecipient

func ( GetCharactersCharacterIdMailMailIdRecipientList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdMailMailIdRecipientList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdMailMailIdRecipientList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdMailMailIdRecipientList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdMailMailIdRecipientList *GetCharactersCharacterIdMailMailIdRecipientList
