// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( InternalServerError ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* InternalServerError ) UnmarshalJSON([]byte) error { return nil }
func ( InternalServerError ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* InternalServerError ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_InternalServerError *InternalServerError

func ( InternalServerErrorList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* InternalServerErrorList ) UnmarshalJSON([]byte) error { return nil }
func ( InternalServerErrorList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* InternalServerErrorList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_InternalServerErrorList *InternalServerErrorList
