// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( PostUniverseIdsFaction ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostUniverseIdsFaction ) UnmarshalJSON([]byte) error { return nil }
func ( PostUniverseIdsFaction ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostUniverseIdsFaction ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostUniverseIdsFaction *PostUniverseIdsFaction

func ( PostUniverseIdsFactionList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostUniverseIdsFactionList ) UnmarshalJSON([]byte) error { return nil }
func ( PostUniverseIdsFactionList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostUniverseIdsFactionList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostUniverseIdsFactionList *PostUniverseIdsFactionList
