// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCorporationsCorporationIdFwStatsOk ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdFwStatsOk ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdFwStatsOk ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdFwStatsOk ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdFwStatsOk *GetCorporationsCorporationIdFwStatsOk

func ( GetCorporationsCorporationIdFwStatsOkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdFwStatsOkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdFwStatsOkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdFwStatsOkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdFwStatsOkList *GetCorporationsCorporationIdFwStatsOkList
