// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCorporationsCorporationIdContracts200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdContracts200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdContracts200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdContracts200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdContracts200Ok *GetCorporationsCorporationIdContracts200Ok

func ( GetCorporationsCorporationIdContracts200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdContracts200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdContracts200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdContracts200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdContracts200OkList *GetCorporationsCorporationIdContracts200OkList
