// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCorporationsCorporationIdAlliancehistory200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdAlliancehistory200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdAlliancehistory200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdAlliancehistory200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdAlliancehistory200Ok *GetCorporationsCorporationIdAlliancehistory200Ok

func ( GetCorporationsCorporationIdAlliancehistory200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdAlliancehistory200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdAlliancehistory200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdAlliancehistory200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdAlliancehistory200OkList *GetCorporationsCorporationIdAlliancehistory200OkList
