// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( PostFleetsFleetIdWingsWingIdSquadsCreated ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostFleetsFleetIdWingsWingIdSquadsCreated ) UnmarshalJSON([]byte) error { return nil }
func ( PostFleetsFleetIdWingsWingIdSquadsCreated ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostFleetsFleetIdWingsWingIdSquadsCreated ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostFleetsFleetIdWingsWingIdSquadsCreated *PostFleetsFleetIdWingsWingIdSquadsCreated

func ( PostFleetsFleetIdWingsWingIdSquadsCreatedList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostFleetsFleetIdWingsWingIdSquadsCreatedList ) UnmarshalJSON([]byte) error { return nil }
func ( PostFleetsFleetIdWingsWingIdSquadsCreatedList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostFleetsFleetIdWingsWingIdSquadsCreatedList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostFleetsFleetIdWingsWingIdSquadsCreatedList *PostFleetsFleetIdWingsWingIdSquadsCreatedList
