// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetUniverseConstellationsConstellationIdPosition ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseConstellationsConstellationIdPosition ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseConstellationsConstellationIdPosition ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseConstellationsConstellationIdPosition ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseConstellationsConstellationIdPosition *GetUniverseConstellationsConstellationIdPosition

func ( GetUniverseConstellationsConstellationIdPositionList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseConstellationsConstellationIdPositionList ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseConstellationsConstellationIdPositionList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseConstellationsConstellationIdPositionList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseConstellationsConstellationIdPositionList *GetUniverseConstellationsConstellationIdPositionList
