// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetUniverseStargatesStargateIdPosition ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseStargatesStargateIdPosition ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseStargatesStargateIdPosition ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseStargatesStargateIdPosition ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseStargatesStargateIdPosition *GetUniverseStargatesStargateIdPosition

func ( GetUniverseStargatesStargateIdPositionList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseStargatesStargateIdPositionList ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseStargatesStargateIdPositionList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseStargatesStargateIdPositionList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseStargatesStargateIdPositionList *GetUniverseStargatesStargateIdPositionList
