// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCorporationsCorporationIdDivisionsWalletWallet ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdDivisionsWalletWallet ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdDivisionsWalletWallet ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdDivisionsWalletWallet ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdDivisionsWalletWallet *GetCorporationsCorporationIdDivisionsWalletWallet

func ( GetCorporationsCorporationIdDivisionsWalletWalletList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdDivisionsWalletWalletList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdDivisionsWalletWalletList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdDivisionsWalletWalletList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdDivisionsWalletWalletList *GetCorporationsCorporationIdDivisionsWalletWalletList
