// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( PostFleetsFleetIdMembersNotFound ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostFleetsFleetIdMembersNotFound ) UnmarshalJSON([]byte) error { return nil }
func ( PostFleetsFleetIdMembersNotFound ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostFleetsFleetIdMembersNotFound ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostFleetsFleetIdMembersNotFound *PostFleetsFleetIdMembersNotFound

func ( PostFleetsFleetIdMembersNotFoundList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostFleetsFleetIdMembersNotFoundList ) UnmarshalJSON([]byte) error { return nil }
func ( PostFleetsFleetIdMembersNotFoundList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostFleetsFleetIdMembersNotFoundList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostFleetsFleetIdMembersNotFoundList *PostFleetsFleetIdMembersNotFoundList
