// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetUniverseTypesTypeIdDogmaAttribute ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseTypesTypeIdDogmaAttribute ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseTypesTypeIdDogmaAttribute ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseTypesTypeIdDogmaAttribute ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseTypesTypeIdDogmaAttribute *GetUniverseTypesTypeIdDogmaAttribute

func ( GetUniverseTypesTypeIdDogmaAttributeList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseTypesTypeIdDogmaAttributeList ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseTypesTypeIdDogmaAttributeList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseTypesTypeIdDogmaAttributeList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseTypesTypeIdDogmaAttributeList *GetUniverseTypesTypeIdDogmaAttributeList
