// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( PostFleetsFleetIdWingsWingIdSquadsNotFound ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostFleetsFleetIdWingsWingIdSquadsNotFound ) UnmarshalJSON([]byte) error { return nil }
func ( PostFleetsFleetIdWingsWingIdSquadsNotFound ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostFleetsFleetIdWingsWingIdSquadsNotFound ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostFleetsFleetIdWingsWingIdSquadsNotFound *PostFleetsFleetIdWingsWingIdSquadsNotFound

func ( PostFleetsFleetIdWingsWingIdSquadsNotFoundList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostFleetsFleetIdWingsWingIdSquadsNotFoundList ) UnmarshalJSON([]byte) error { return nil }
func ( PostFleetsFleetIdWingsWingIdSquadsNotFoundList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostFleetsFleetIdWingsWingIdSquadsNotFoundList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostFleetsFleetIdWingsWingIdSquadsNotFoundList *PostFleetsFleetIdWingsWingIdSquadsNotFoundList
