// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetMarketsRegionIdHistory200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetMarketsRegionIdHistory200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetMarketsRegionIdHistory200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetMarketsRegionIdHistory200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetMarketsRegionIdHistory200Ok *GetMarketsRegionIdHistory200Ok

func ( GetMarketsRegionIdHistory200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetMarketsRegionIdHistory200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetMarketsRegionIdHistory200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetMarketsRegionIdHistory200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetMarketsRegionIdHistory200OkList *GetMarketsRegionIdHistory200OkList
