// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCharactersCharacterIdContractsContractIdBidsNotFound ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdContractsContractIdBidsNotFound ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdContractsContractIdBidsNotFound ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdContractsContractIdBidsNotFound ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdContractsContractIdBidsNotFound *GetCharactersCharacterIdContractsContractIdBidsNotFound

func ( GetCharactersCharacterIdContractsContractIdBidsNotFoundList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdContractsContractIdBidsNotFoundList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdContractsContractIdBidsNotFoundList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdContractsContractIdBidsNotFoundList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdContractsContractIdBidsNotFoundList *GetCharactersCharacterIdContractsContractIdBidsNotFoundList
