// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetUniverseSchematicsSchematicIdOk ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseSchematicsSchematicIdOk ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseSchematicsSchematicIdOk ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseSchematicsSchematicIdOk ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseSchematicsSchematicIdOk *GetUniverseSchematicsSchematicIdOk

func ( GetUniverseSchematicsSchematicIdOkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseSchematicsSchematicIdOkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseSchematicsSchematicIdOkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseSchematicsSchematicIdOkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseSchematicsSchematicIdOkList *GetUniverseSchematicsSchematicIdOkList
