// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCorporationsCorporationIdContactsLabels200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdContactsLabels200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdContactsLabels200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdContactsLabels200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdContactsLabels200Ok *GetCorporationsCorporationIdContactsLabels200Ok

func ( GetCorporationsCorporationIdContactsLabels200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdContactsLabels200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdContactsLabels200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdContactsLabels200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdContactsLabels200OkList *GetCorporationsCorporationIdContactsLabels200OkList
