// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetDogmaDynamicItemsTypeIdItemIdDogmaAttribute ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetDogmaDynamicItemsTypeIdItemIdDogmaAttribute ) UnmarshalJSON([]byte) error { return nil }
func ( GetDogmaDynamicItemsTypeIdItemIdDogmaAttribute ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetDogmaDynamicItemsTypeIdItemIdDogmaAttribute ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetDogmaDynamicItemsTypeIdItemIdDogmaAttribute *GetDogmaDynamicItemsTypeIdItemIdDogmaAttribute

func ( GetDogmaDynamicItemsTypeIdItemIdDogmaAttributeList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetDogmaDynamicItemsTypeIdItemIdDogmaAttributeList ) UnmarshalJSON([]byte) error { return nil }
func ( GetDogmaDynamicItemsTypeIdItemIdDogmaAttributeList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetDogmaDynamicItemsTypeIdItemIdDogmaAttributeList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetDogmaDynamicItemsTypeIdItemIdDogmaAttributeList *GetDogmaDynamicItemsTypeIdItemIdDogmaAttributeList
