// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetContractsPublicBidsContractId200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetContractsPublicBidsContractId200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetContractsPublicBidsContractId200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetContractsPublicBidsContractId200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetContractsPublicBidsContractId200Ok *GetContractsPublicBidsContractId200Ok

func ( GetContractsPublicBidsContractId200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetContractsPublicBidsContractId200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetContractsPublicBidsContractId200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetContractsPublicBidsContractId200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetContractsPublicBidsContractId200OkList *GetContractsPublicBidsContractId200OkList
