// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetMarketsRegionIdHistoryUnprocessableEntity ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetMarketsRegionIdHistoryUnprocessableEntity ) UnmarshalJSON([]byte) error { return nil }
func ( GetMarketsRegionIdHistoryUnprocessableEntity ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetMarketsRegionIdHistoryUnprocessableEntity ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetMarketsRegionIdHistoryUnprocessableEntity *GetMarketsRegionIdHistoryUnprocessableEntity

func ( GetMarketsRegionIdHistoryUnprocessableEntityList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetMarketsRegionIdHistoryUnprocessableEntityList ) UnmarshalJSON([]byte) error { return nil }
func ( GetMarketsRegionIdHistoryUnprocessableEntityList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetMarketsRegionIdHistoryUnprocessableEntityList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetMarketsRegionIdHistoryUnprocessableEntityList *GetMarketsRegionIdHistoryUnprocessableEntityList
