// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetAlliancesAllianceIdContacts200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetAlliancesAllianceIdContacts200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetAlliancesAllianceIdContacts200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetAlliancesAllianceIdContacts200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetAlliancesAllianceIdContacts200Ok *GetAlliancesAllianceIdContacts200Ok

func ( GetAlliancesAllianceIdContacts200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetAlliancesAllianceIdContacts200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetAlliancesAllianceIdContacts200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetAlliancesAllianceIdContacts200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetAlliancesAllianceIdContacts200OkList *GetAlliancesAllianceIdContacts200OkList
