// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetKillmailsKillmailIdKillmailHashItem ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetKillmailsKillmailIdKillmailHashItem ) UnmarshalJSON([]byte) error { return nil }
func ( GetKillmailsKillmailIdKillmailHashItem ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetKillmailsKillmailIdKillmailHashItem ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetKillmailsKillmailIdKillmailHashItem *GetKillmailsKillmailIdKillmailHashItem

func ( GetKillmailsKillmailIdKillmailHashItemList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetKillmailsKillmailIdKillmailHashItemList ) UnmarshalJSON([]byte) error { return nil }
func ( GetKillmailsKillmailIdKillmailHashItemList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetKillmailsKillmailIdKillmailHashItemList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetKillmailsKillmailIdKillmailHashItemList *GetKillmailsKillmailIdKillmailHashItemList
