// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( PostCorporationsCorporationIdAssetsNamesNotFound ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostCorporationsCorporationIdAssetsNamesNotFound ) UnmarshalJSON([]byte) error { return nil }
func ( PostCorporationsCorporationIdAssetsNamesNotFound ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostCorporationsCorporationIdAssetsNamesNotFound ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostCorporationsCorporationIdAssetsNamesNotFound *PostCorporationsCorporationIdAssetsNamesNotFound

func ( PostCorporationsCorporationIdAssetsNamesNotFoundList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostCorporationsCorporationIdAssetsNamesNotFoundList ) UnmarshalJSON([]byte) error { return nil }
func ( PostCorporationsCorporationIdAssetsNamesNotFoundList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostCorporationsCorporationIdAssetsNamesNotFoundList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostCorporationsCorporationIdAssetsNamesNotFoundList *PostCorporationsCorporationIdAssetsNamesNotFoundList
