// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCorporationsCorporationIdMedals200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdMedals200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdMedals200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdMedals200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdMedals200Ok *GetCorporationsCorporationIdMedals200Ok

func ( GetCorporationsCorporationIdMedals200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdMedals200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdMedals200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdMedals200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdMedals200OkList *GetCorporationsCorporationIdMedals200OkList
