// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( PostCorporationsCorporationIdAssetsLocations200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostCorporationsCorporationIdAssetsLocations200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( PostCorporationsCorporationIdAssetsLocations200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostCorporationsCorporationIdAssetsLocations200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostCorporationsCorporationIdAssetsLocations200Ok *PostCorporationsCorporationIdAssetsLocations200Ok

func ( PostCorporationsCorporationIdAssetsLocations200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostCorporationsCorporationIdAssetsLocations200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( PostCorporationsCorporationIdAssetsLocations200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostCorporationsCorporationIdAssetsLocations200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostCorporationsCorporationIdAssetsLocations200OkList *PostCorporationsCorporationIdAssetsLocations200OkList
