// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetAlliancesAllianceIdNotFound ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetAlliancesAllianceIdNotFound ) UnmarshalJSON([]byte) error { return nil }
func ( GetAlliancesAllianceIdNotFound ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetAlliancesAllianceIdNotFound ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetAlliancesAllianceIdNotFound *GetAlliancesAllianceIdNotFound

func ( GetAlliancesAllianceIdNotFoundList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetAlliancesAllianceIdNotFoundList ) UnmarshalJSON([]byte) error { return nil }
func ( GetAlliancesAllianceIdNotFoundList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetAlliancesAllianceIdNotFoundList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetAlliancesAllianceIdNotFoundList *GetAlliancesAllianceIdNotFoundList
