// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetUniverseCategoriesCategoryIdNotFound ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseCategoriesCategoryIdNotFound ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseCategoriesCategoryIdNotFound ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseCategoriesCategoryIdNotFound ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseCategoriesCategoryIdNotFound *GetUniverseCategoriesCategoryIdNotFound

func ( GetUniverseCategoriesCategoryIdNotFoundList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseCategoriesCategoryIdNotFoundList ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseCategoriesCategoryIdNotFoundList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseCategoriesCategoryIdNotFoundList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseCategoriesCategoryIdNotFoundList *GetUniverseCategoriesCategoryIdNotFoundList
