// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetUniverseAncestries200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseAncestries200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseAncestries200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseAncestries200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseAncestries200Ok *GetUniverseAncestries200Ok

func ( GetUniverseAncestries200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseAncestries200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseAncestries200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseAncestries200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseAncestries200OkList *GetUniverseAncestries200OkList
