// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCorporationsCorporationIdBookmarksFolders200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdBookmarksFolders200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdBookmarksFolders200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdBookmarksFolders200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdBookmarksFolders200Ok *GetCorporationsCorporationIdBookmarksFolders200Ok

func ( GetCorporationsCorporationIdBookmarksFolders200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdBookmarksFolders200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdBookmarksFolders200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdBookmarksFolders200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdBookmarksFolders200OkList *GetCorporationsCorporationIdBookmarksFolders200OkList
