// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCharactersCharacterIdBookmarksFolders200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdBookmarksFolders200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdBookmarksFolders200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdBookmarksFolders200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdBookmarksFolders200Ok *GetCharactersCharacterIdBookmarksFolders200Ok

func ( GetCharactersCharacterIdBookmarksFolders200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdBookmarksFolders200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdBookmarksFolders200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdBookmarksFolders200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdBookmarksFolders200OkList *GetCharactersCharacterIdBookmarksFolders200OkList
