// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCorporationsCorporationIdBookmarks200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdBookmarks200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdBookmarks200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdBookmarks200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdBookmarks200Ok *GetCorporationsCorporationIdBookmarks200Ok

func ( GetCorporationsCorporationIdBookmarks200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdBookmarks200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdBookmarks200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdBookmarks200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdBookmarks200OkList *GetCorporationsCorporationIdBookmarks200OkList
