// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetMarketsRegionIdOrdersNotFound ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetMarketsRegionIdOrdersNotFound ) UnmarshalJSON([]byte) error { return nil }
func ( GetMarketsRegionIdOrdersNotFound ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetMarketsRegionIdOrdersNotFound ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetMarketsRegionIdOrdersNotFound *GetMarketsRegionIdOrdersNotFound

func ( GetMarketsRegionIdOrdersNotFoundList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetMarketsRegionIdOrdersNotFoundList ) UnmarshalJSON([]byte) error { return nil }
func ( GetMarketsRegionIdOrdersNotFoundList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetMarketsRegionIdOrdersNotFoundList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetMarketsRegionIdOrdersNotFoundList *GetMarketsRegionIdOrdersNotFoundList
