// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( BadRequest ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* BadRequest ) UnmarshalJSON([]byte) error { return nil }
func ( BadRequest ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* BadRequest ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_BadRequest *BadRequest

func ( BadRequestList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* BadRequestList ) UnmarshalJSON([]byte) error { return nil }
func ( BadRequestList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* BadRequestList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_BadRequestList *BadRequestList
