// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCharactersCharacterIdStandings200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdStandings200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdStandings200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdStandings200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdStandings200Ok *GetCharactersCharacterIdStandings200Ok

func ( GetCharactersCharacterIdStandings200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdStandings200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdStandings200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdStandings200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdStandings200OkList *GetCharactersCharacterIdStandings200OkList
