// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( PostCharactersCharacterIdMailRecipient ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostCharactersCharacterIdMailRecipient ) UnmarshalJSON([]byte) error { return nil }
func ( PostCharactersCharacterIdMailRecipient ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostCharactersCharacterIdMailRecipient ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostCharactersCharacterIdMailRecipient *PostCharactersCharacterIdMailRecipient

func ( PostCharactersCharacterIdMailRecipientList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostCharactersCharacterIdMailRecipientList ) UnmarshalJSON([]byte) error { return nil }
func ( PostCharactersCharacterIdMailRecipientList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostCharactersCharacterIdMailRecipientList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostCharactersCharacterIdMailRecipientList *PostCharactersCharacterIdMailRecipientList
