// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetUniverseGroupsGroupIdNotFound ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseGroupsGroupIdNotFound ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseGroupsGroupIdNotFound ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseGroupsGroupIdNotFound ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseGroupsGroupIdNotFound *GetUniverseGroupsGroupIdNotFound

func ( GetUniverseGroupsGroupIdNotFoundList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseGroupsGroupIdNotFoundList ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseGroupsGroupIdNotFoundList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseGroupsGroupIdNotFoundList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseGroupsGroupIdNotFoundList *GetUniverseGroupsGroupIdNotFoundList
