// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetMarketsStructuresStructureId200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetMarketsStructuresStructureId200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetMarketsStructuresStructureId200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetMarketsStructuresStructureId200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetMarketsStructuresStructureId200Ok *GetMarketsStructuresStructureId200Ok

func ( GetMarketsStructuresStructureId200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetMarketsStructuresStructureId200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetMarketsStructuresStructureId200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetMarketsStructuresStructureId200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetMarketsStructuresStructureId200OkList *GetMarketsStructuresStructureId200OkList
