// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCharactersCharacterIdRolesOk ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdRolesOk ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdRolesOk ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdRolesOk ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdRolesOk *GetCharactersCharacterIdRolesOk

func ( GetCharactersCharacterIdRolesOkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdRolesOkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdRolesOkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdRolesOkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdRolesOkList *GetCharactersCharacterIdRolesOkList
