// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( Forbidden ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Forbidden ) UnmarshalJSON([]byte) error { return nil }
func ( Forbidden ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Forbidden ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Forbidden *Forbidden

func ( ForbiddenList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* ForbiddenList ) UnmarshalJSON([]byte) error { return nil }
func ( ForbiddenList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* ForbiddenList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ForbiddenList *ForbiddenList
