// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCorporationsCorporationIdContractsContractIdItemsError520 ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdContractsContractIdItemsError520 ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdContractsContractIdItemsError520 ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdContractsContractIdItemsError520 ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdContractsContractIdItemsError520 *GetCorporationsCorporationIdContractsContractIdItemsError520

func ( GetCorporationsCorporationIdContractsContractIdItemsError520List ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdContractsContractIdItemsError520List ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdContractsContractIdItemsError520List ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdContractsContractIdItemsError520List ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdContractsContractIdItemsError520List *GetCorporationsCorporationIdContractsContractIdItemsError520List
