// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( PutCharactersCharacterIdMailMailIdContents ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PutCharactersCharacterIdMailMailIdContents ) UnmarshalJSON([]byte) error { return nil }
func ( PutCharactersCharacterIdMailMailIdContents ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PutCharactersCharacterIdMailMailIdContents ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PutCharactersCharacterIdMailMailIdContents *PutCharactersCharacterIdMailMailIdContents

func ( PutCharactersCharacterIdMailMailIdContentsList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PutCharactersCharacterIdMailMailIdContentsList ) UnmarshalJSON([]byte) error { return nil }
func ( PutCharactersCharacterIdMailMailIdContentsList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PutCharactersCharacterIdMailMailIdContentsList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PutCharactersCharacterIdMailMailIdContentsList *PutCharactersCharacterIdMailMailIdContentsList
