// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCorporationsCorporationIdBookmarksCoordinates ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdBookmarksCoordinates ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdBookmarksCoordinates ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdBookmarksCoordinates ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdBookmarksCoordinates *GetCorporationsCorporationIdBookmarksCoordinates

func ( GetCorporationsCorporationIdBookmarksCoordinatesList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdBookmarksCoordinatesList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdBookmarksCoordinatesList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdBookmarksCoordinatesList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdBookmarksCoordinatesList *GetCorporationsCorporationIdBookmarksCoordinatesList
