// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetInsurancePricesLevel ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetInsurancePricesLevel ) UnmarshalJSON([]byte) error { return nil }
func ( GetInsurancePricesLevel ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetInsurancePricesLevel ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetInsurancePricesLevel *GetInsurancePricesLevel

func ( GetInsurancePricesLevelList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetInsurancePricesLevelList ) UnmarshalJSON([]byte) error { return nil }
func ( GetInsurancePricesLevelList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetInsurancePricesLevelList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetInsurancePricesLevelList *GetInsurancePricesLevelList
