// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCorporationsCorporationIdDivisionsHangarHangar ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdDivisionsHangarHangar ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdDivisionsHangarHangar ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdDivisionsHangarHangar ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdDivisionsHangarHangar *GetCorporationsCorporationIdDivisionsHangarHangar

func ( GetCorporationsCorporationIdDivisionsHangarHangarList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCorporationsCorporationIdDivisionsHangarHangarList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCorporationsCorporationIdDivisionsHangarHangarList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCorporationsCorporationIdDivisionsHangarHangarList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCorporationsCorporationIdDivisionsHangarHangarList *GetCorporationsCorporationIdDivisionsHangarHangarList
