// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetUniverseTypesTypeIdOk ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseTypesTypeIdOk ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseTypesTypeIdOk ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseTypesTypeIdOk ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseTypesTypeIdOk *GetUniverseTypesTypeIdOk

func ( GetUniverseTypesTypeIdOkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseTypesTypeIdOkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseTypesTypeIdOkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseTypesTypeIdOkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseTypesTypeIdOkList *GetUniverseTypesTypeIdOkList
