// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCharactersCharacterIdPlanetsPlanetIdLink ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdPlanetsPlanetIdLink ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdPlanetsPlanetIdLink ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdPlanetsPlanetIdLink ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdPlanetsPlanetIdLink *GetCharactersCharacterIdPlanetsPlanetIdLink

func ( GetCharactersCharacterIdPlanetsPlanetIdLinkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdPlanetsPlanetIdLinkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdPlanetsPlanetIdLinkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdPlanetsPlanetIdLinkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdPlanetsPlanetIdLinkList *GetCharactersCharacterIdPlanetsPlanetIdLinkList
