// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( PostUniverseIdsInventoryType ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostUniverseIdsInventoryType ) UnmarshalJSON([]byte) error { return nil }
func ( PostUniverseIdsInventoryType ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostUniverseIdsInventoryType ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostUniverseIdsInventoryType *PostUniverseIdsInventoryType

func ( PostUniverseIdsInventoryTypeList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostUniverseIdsInventoryTypeList ) UnmarshalJSON([]byte) error { return nil }
func ( PostUniverseIdsInventoryTypeList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostUniverseIdsInventoryTypeList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostUniverseIdsInventoryTypeList *PostUniverseIdsInventoryTypeList
