// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetSovereigntyCampaignsParticipant ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetSovereigntyCampaignsParticipant ) UnmarshalJSON([]byte) error { return nil }
func ( GetSovereigntyCampaignsParticipant ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetSovereigntyCampaignsParticipant ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetSovereigntyCampaignsParticipant *GetSovereigntyCampaignsParticipant

func ( GetSovereigntyCampaignsParticipantList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetSovereigntyCampaignsParticipantList ) UnmarshalJSON([]byte) error { return nil }
func ( GetSovereigntyCampaignsParticipantList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetSovereigntyCampaignsParticipantList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetSovereigntyCampaignsParticipantList *GetSovereigntyCampaignsParticipantList
