// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetOpportunitiesTasksTaskIdOk ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetOpportunitiesTasksTaskIdOk ) UnmarshalJSON([]byte) error { return nil }
func ( GetOpportunitiesTasksTaskIdOk ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetOpportunitiesTasksTaskIdOk ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetOpportunitiesTasksTaskIdOk *GetOpportunitiesTasksTaskIdOk

func ( GetOpportunitiesTasksTaskIdOkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetOpportunitiesTasksTaskIdOkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetOpportunitiesTasksTaskIdOkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetOpportunitiesTasksTaskIdOkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetOpportunitiesTasksTaskIdOkList *GetOpportunitiesTasksTaskIdOkList
