// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetUniverseStargatesStargateIdNotFound ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseStargatesStargateIdNotFound ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseStargatesStargateIdNotFound ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseStargatesStargateIdNotFound ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseStargatesStargateIdNotFound *GetUniverseStargatesStargateIdNotFound

func ( GetUniverseStargatesStargateIdNotFoundList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseStargatesStargateIdNotFoundList ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseStargatesStargateIdNotFoundList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseStargatesStargateIdNotFoundList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseStargatesStargateIdNotFoundList *GetUniverseStargatesStargateIdNotFoundList
