// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCharactersCharacterIdLoyaltyPoints200Ok ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdLoyaltyPoints200Ok ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdLoyaltyPoints200Ok ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdLoyaltyPoints200Ok ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdLoyaltyPoints200Ok *GetCharactersCharacterIdLoyaltyPoints200Ok

func ( GetCharactersCharacterIdLoyaltyPoints200OkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdLoyaltyPoints200OkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdLoyaltyPoints200OkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdLoyaltyPoints200OkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdLoyaltyPoints200OkList *GetCharactersCharacterIdLoyaltyPoints200OkList
