// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( PostUniverseIdsConstellation ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostUniverseIdsConstellation ) UnmarshalJSON([]byte) error { return nil }
func ( PostUniverseIdsConstellation ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostUniverseIdsConstellation ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostUniverseIdsConstellation *PostUniverseIdsConstellation

func ( PostUniverseIdsConstellationList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostUniverseIdsConstellationList ) UnmarshalJSON([]byte) error { return nil }
func ( PostUniverseIdsConstellationList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostUniverseIdsConstellationList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostUniverseIdsConstellationList *PostUniverseIdsConstellationList
