// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCharactersCharacterIdBookmarksItem ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdBookmarksItem ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdBookmarksItem ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdBookmarksItem ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdBookmarksItem *GetCharactersCharacterIdBookmarksItem

func ( GetCharactersCharacterIdBookmarksItemList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdBookmarksItemList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdBookmarksItemList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdBookmarksItemList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdBookmarksItemList *GetCharactersCharacterIdBookmarksItemList
