// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetCharactersCharacterIdClonesHomeLocation ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdClonesHomeLocation ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdClonesHomeLocation ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdClonesHomeLocation ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdClonesHomeLocation *GetCharactersCharacterIdClonesHomeLocation

func ( GetCharactersCharacterIdClonesHomeLocationList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCharactersCharacterIdClonesHomeLocationList ) UnmarshalJSON([]byte) error { return nil }
func ( GetCharactersCharacterIdClonesHomeLocationList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCharactersCharacterIdClonesHomeLocationList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCharactersCharacterIdClonesHomeLocationList *GetCharactersCharacterIdClonesHomeLocationList
