// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetUniverseMoonsMoonIdOk ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseMoonsMoonIdOk ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseMoonsMoonIdOk ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseMoonsMoonIdOk ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseMoonsMoonIdOk *GetUniverseMoonsMoonIdOk

func ( GetUniverseMoonsMoonIdOkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseMoonsMoonIdOkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseMoonsMoonIdOkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseMoonsMoonIdOkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseMoonsMoonIdOkList *GetUniverseMoonsMoonIdOkList
