// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  esi

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetUniverseAsteroidBeltsAsteroidBeltIdOk ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseAsteroidBeltsAsteroidBeltIdOk ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseAsteroidBeltsAsteroidBeltIdOk ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseAsteroidBeltsAsteroidBeltIdOk ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseAsteroidBeltsAsteroidBeltIdOk *GetUniverseAsteroidBeltsAsteroidBeltIdOk

func ( GetUniverseAsteroidBeltsAsteroidBeltIdOkList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetUniverseAsteroidBeltsAsteroidBeltIdOkList ) UnmarshalJSON([]byte) error { return nil }
func ( GetUniverseAsteroidBeltsAsteroidBeltIdOkList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetUniverseAsteroidBeltsAsteroidBeltIdOkList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetUniverseAsteroidBeltsAsteroidBeltIdOkList *GetUniverseAsteroidBeltsAsteroidBeltIdOkList
